In [1]:
import pandas as pd

In [2]:
#load Dataset
data_analyst_df = pd.read_csv('/Users/akshaytayde/neuefische/Capstone-Project-/dataset/DataAnalyst.csv')
data_scientist_df = pd.read_csv('/Users/akshaytayde/neuefische/Capstone-Project-/dataset/DataScientist.csv')
google_job = pd.read_csv('/Users/akshaytayde/neuefische/Capstone-Project-/dataset/gsearch_jobs 3.csv')

In [3]:
#Rename Columns to lower and replace white spaces with Underscore
data_analyst_df.rename(columns=lambda x : x.lower(), inplace=True)
data_analyst_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
data_scientist_df.rename(columns=lambda x : x.lower(), inplace=True)
data_scientist_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
google_job.rename(columns=lambda x : x.lower(), inplace=True)
google_job.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)

In [4]:
data_analyst_df2 = data_analyst_df[['job_title', 'job_description']].copy()
data_scientist_df2 = data_scientist_df[['job_title', 'job_description']].copy()
google_job_df2 = google_job[['title', 'description']].copy()

In [5]:
data_analyst_df2.head()

,job_title,job_description
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...

In [6]:
#Join Data Analyst Dataset and Data Scientist Dataset
analyst_scientist_df = pd.concat([data_analyst_df2, data_scientist_df2], ignore_index=True)

In [7]:
analyst_scientist_df.head()

,job_title,job_description
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...

In [8]:
#lets rename columns of the google job dataset
google_job_df2 = google_job_df2.rename(columns={'title': 'job_title', 'description': 'job_description'})

In [9]:
#join google dataset to the data analyst /scientist dataset
master_df = pd.concat([analyst_scientist_df, google_job_df2], ignore_index=True)

In [10]:
master_df.head()

,job_title,job_description
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...

In [11]:
import string
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

In [12]:
master_df['job_description'] = master_df['job_description'].replace({'/':' ','-':' '},regex=True)

In [13]:
# Import Libraries
import string # a collection of string constraints: white-space, punctuation, etc.
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
#nltk.download('punkt')   # Required for tokenization
#nltk.download('wordnet') # Required for lemmatization
# nltk.download('popular')
from nltk.corpus import stopwords
# Instantiate
lemmatizer = WordNetLemmatizer()
# Create our own stop words
stop_words = (                                        \
    "\n ’ sleeves company and of for in to a or years l   \
    other were that to drive policy we at with our   \
    firm follows under consolidated have these over   \
    include billion million december which an le from \
    certain le — million had show apple including     \
    as noncurrent current total three are on not is   \
    involving millions shows centers contains      "  \
             ).split()
# Exclusion list of punctuations and numbers
# exclist = string.punctuation + string.digits # Do we also need digits?
punctuation = "!$%&'()*,-./:;<=>?@[\]^_`{|}~"
exclist = punctuation  # Do we also need digits?
# Print the exclusion list
print(exclist)

!$%&'()*,-./:;<=>?@[\]^_`{|}~

In [15]:
# Create a Function
def clean_texts(text):
    """ Function to perform preprocessing """
    
    # Convert to lower cases
    text = text.lower()
    
    # Remove punctuations and numbers
    text = text.translate(str.maketrans("", "", punctuation))
    
    # White space before and after punctuation?
    # text = text.translate(str.maketrans({key: " {0} ".format(key) for key in string.punctuation}))
    
    
    # Tokenization
    tokens = word_tokenize(text)
        
    # Lemmatization
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Remove stop words
    stopwords = nltk.corpus.stopwords.words('english')
    tokens = [token for token in tokens if token not in stopwords]
    
    # Join tokens
    clean_text = " ".join(tokens)
    
    # Return the output
    return clean_text
# Apply the function to all disclosures
master_df['clean_description'] = master_df['job_description'].apply(clean_texts)
# View the first 5 rows
master_df.head()

,job_title,job_description,clean_description
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...

In [16]:
# natural language processing: n-gram ranking
import re
import unicodedata
# import nltk
# from nltk.corpus import stopwords# add appropriate words that will be ignored in the analysis
# ADDITIONAL_STOPWORDS = ['covfefe']
import matplotlib.pyplot as plt

def basic_clean(text):
  """
  A simple function to clean up the data. All the words that
  are not designated as a stop word is then lemmatized after
  encoding and basic regex parsing are performed.
  """
  wnl = nltk.stem.WordNetLemmatizer()
  stopwords = nltk.corpus.stopwords.words('english') # + ADDITIONAL_STOPWORDS
  text = (unicodedata.normalize('NFKD', text)
    .encode('ascii', 'ignore')
    .decode('utf-8', 'ignore')
    .lower())
  words = re.sub(r'[^\w\s]', '', text).split()
  return [wnl.lemmatize(word) for word in words if word not in stopwords]
master_df['job_experience'] = master_df['job_description'].apply(basic_clean)
# master_df['two_word_description'] = pd.Series(nltk.ngrams(master_df['two_word_description'], 2))
# master_df['two_word_description'] = master_df['job_description'].apply(nltk.ngrams(master_df), 2)
master_df.head()

,job_title,job_description,clean_description,job_experience
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...,"[eager, roll, sleeve, harness, data, drive, po..."
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...,"[overview, provides, analytical, technical, su..."
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...,"[looking, senior, data, analyst, love, mentors..."
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...,"[requisition, numberrr, 0001939, remoteyes, co..."
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...,"[fanduel, group, fanduel, group, world, class,..."

In [17]:
master_df['job_experience'] = master_df["job_experience"].apply(lambda x:list(nltk.ngrams(x, n=2)))

In [18]:
master_df['job_experience'][0]

[('eager', 'roll'),
 ('roll', 'sleeve'),
 ('sleeve', 'harness'),
 ('harness', 'data'),
 ('data', 'drive'),
 ('drive', 'policy'),
 ('policy', 'change'),
 ('change', 'enjoy'),
 ('enjoy', 'sifting'),
 ('sifting', 'complex'),
 ('complex', 'datasets'),
 ('datasets', 'illuminate'),
 ('illuminate', 'trend'),
 ('trend', 'insight'),
 ('insight', 'see'),
 ('see', 'working'),
 ('working', 'value'),
 ('value', 'driven'),
 ('driven', 'organization'),
 ('organization', 'vision'),
 ('vision', 'tackle'),
 ('tackle', 'pressing'),
 ('pressing', 'injustice'),
 ('injustice', 'day'),
 ('day', 'looking'),
 ('looking', 'hire'),
 ('hire', 'bright'),
 ('bright', 'hard'),
 ('hard', 'working'),
 ('working', 'creative'),
 ('creative', 'individual'),
 ('individual', 'strong'),
 ('strong', 'data'),
 ('data', 'management'),
 ('management', 'skill'),
 ('skill', 'demonstrated'),
 ('demonstrated', 'commitment'),
 ('commitment', 'immigrant'),
 ('immigrant', 'right'),
 ('right', 'data'),
 ('data', 'analyst'),
 ('analyst', 'assist'),
 ('assist', 'analysis'),
 ('analysis', 'reporting'),
 ('reporting', 'need'),
 ('need', 'veras'),
 ('veras', 'center'),
 ('center', 'immigration'),
 ('immigration', 'justice'),
 ('justice', 'cij'),
 ('cij', 'working'),
 ('working', 'across'),
 ('across', 'current'),
 ('current', 'project'),
 ('project', 'future'),
 ('future', 'vera'),
 ('vera', 'initiative'),
 ('initiative', 'founded'),
 ('founded', '1961'),
 ('1961', 'vera'),
 ('vera', 'institute'),
 ('institute', 'independent'),
 ('independent', 'non'),
 ('non', 'partisan'),
 ('partisan', 'nonprofit'),
 ('nonprofit', 'organization'),
 ('organization', 'combine'),
 ('combine', 'expertise'),
 ('expertise', 'research'),
 ('research', 'technical'),
 ('technical', 'assistance'),
 ('assistance', 'demonstration'),
 ('demonstration', 'project'),
 ('project', 'assist'),
 ('assist', 'leader'),
 ('leader', 'government'),
 ('government', 'civil'),
 ('civil', 'society'),
 ('society', 'examine'),
 ('examine', 'justice'),
 ('justice', 'policy'),
 ('policy', 'practice'),
 ('practice', 'improve'),
 ('improve', 'system'),
 ('system', 'people'),
 ('people', 'rely'),
 ('rely', 'justice'),
 ('justice', 'safety'),
 ('safety', 'study'),
 ('study', 'problem'),
 ('problem', 'impede'),
 ('impede', 'human'),
 ('human', 'dignity'),
 ('dignity', 'justice'),
 ('justice', 'pilot'),
 ('pilot', 'solution'),
 ('solution', 'transformative'),
 ('transformative', 'achievable'),
 ('achievable', 'engage'),
 ('engage', 'diverse'),
 ('diverse', 'community'),
 ('community', 'informed'),
 ('informed', 'debate'),
 ('debate', 'harness'),
 ('harness', 'power'),
 ('power', 'evidence'),
 ('evidence', 'drive'),
 ('drive', 'effective'),
 ('effective', 'policy'),
 ('policy', 'practice'),
 ('practice', 'helping'),
 ('helping', 'build'),
 ('build', 'movementamong'),
 ('movementamong', 'government'),
 ('government', 'leader'),
 ('leader', 'advocate'),
 ('advocate', 'immigration'),
 ('immigration', 'legal'),
 ('legal', 'service'),
 ('service', 'communitytowards'),
 ('communitytowards', 'universal'),
 ('universal', 'legal'),
 ('legal', 'representation'),
 ('representation', 'immigrant'),
 ('immigrant', 'facing'),
 ('facing', 'deportation'),
 ('deportation', 'face'),
 ('face', 'stepped'),
 ('stepped', 'immigration'),
 ('immigration', 'enforcement'),
 ('enforcement', 'million'),
 ('million', 'non'),
 ('non', 'citizen'),
 ('citizen', 'risk'),
 ('risk', 'extended'),
 ('extended', 'detention'),
 ('detention', 'permanent'),
 ('permanent', 'separation'),
 ('separation', 'family'),
 ('family', 'community'),
 ('community', 'veras'),
 ('veras', 'center'),
 ('center', 'immigration'),
 ('immigration', 'justice'),
 ('justice', 'cij'),
 ('cij', 'partner'),
 ('partner', 'government'),
 ('government', 'non'),
 ('non', 'profit'),
 ('profit', 'partner'),
 ('partner', 'community'),
 ('community', 'improve'),
 ('improve', 'government'),
 ('government', 'system'),
 ('system', 'affect'),
 ('affect', 'immigrant'),
 ('immigrant', 'family'),
 ('family', 'cij'),
 ('cij', 'administers'),
 ('administers', 'several'),
 ('several', 'nationwide'),
 ('nationwide', 'legal'),
 ('legal', 'service'),
 ('service', 'program'),
 ('program', 'immigrant'),
 ('immigrant', 'facing'),
 ('facing', 'deportation'),
 ('deportation', 'develops'),
 ('develops', 'implement'),
 ('implement', 'pilot'),
 ('pilot', 'program'),
 ('program', 'provides'),
 ('provides', 'technical'),
 ('technical', 'assistance'),
 ('assistance', 'conduct'),
 ('conduct', 'independent'),
 ('independent', 'research'),
 ('research', 'evaluation'),
 ('evaluation', 'thats'),
 ('thats', 'come'),
 ('come', 'data'),
 ('data', 'analyst'),
 ('analyst', 'support'),
 ('support', 'center'),
 ('center', 'programmatic'),
 ('programmatic', 'effort'),
 ('effort', 'regular'),
 ('regular', 'monitoring'),
 ('monitoring', 'reporting'),
 ('reporting', 'federal'),
 ('federal', 'government'),
 ('government', 'subcontractor'),
 ('subcontractor', 'data'),
 ('data', 'cij'),
 ('cij', 'manages'),
 ('manages', 'several'),
 ('several', 'proprietary'),
 ('proprietary', 'database'),
 ('database', 'run'),
 ('run', 'aws'),
 ('aws', 'caspio'),
 ('caspio', 'us'),
 ('us', 'sql'),
 ('sql', 'r'),
 ('r', 'python'),
 ('python', 'manage'),
 ('manage', 'data'),
 ('data', 'opportunity'),
 ('opportunity', 'help'),
 ('help', 'shape'),
 ('shape', 'innovative'),
 ('innovative', 'national'),
 ('national', 'research'),
 ('research', 'policy'),
 ('policy', 'agenda'),
 ('agenda', 'part'),
 ('part', 'dedicated'),
 ('dedicated', 'team'),
 ('team', 'expert'),
 ('expert', 'working'),
 ('working', 'improve'),
 ('improve', 'access'),
 ('access', 'justice'),
 ('justice', 'non'),
 ('non', 'citizen'),
 ('citizen', 'vera'),
 ('vera', 'seek'),
 ('seek', 'hire'),
 ('hire', 'data'),
 ('data', 'analyst'),
 ('analyst', 'work'),
 ('work', 'various'),
 ('various', 'data'),
 ('data', 'management'),
 ('management', 'project'),
 ('project', 'center'),
 ('center', 'immigration'),
 ('immigration', 'justice'),
 ('justice', 'cij'),
 ('cij', 'collaboration'),
 ('collaboration', 'data'),
 ('data', 'analyst'),
 ('analyst', 'position'),
 ('position', 'involve'),
 ('involve', 'work'),
 ('work', 'across'),
 ('across', 'several'),
 ('several', 'project'),
 ('project', 'unaccompanied'),
 ('unaccompanied', 'childrens'),
 ('childrens', 'program'),
 ('program', 'ucp'),
 ('ucp', 'program'),
 ('program', 'increase'),
 ('increase', 'legal'),
 ('legal', 'representation'),
 ('representation', 'immigrant'),
 ('immigrant', 'child'),
 ('child', 'facing'),
 ('facing', 'deportation'),
 ('deportation', 'without'),
 ('without', 'parent'),
 ('parent', 'legal'),
 ('legal', 'guardian'),
 ('guardian', 'position'),
 ('position', 'may'),
 ('may', 'cover'),
 ('cover', 'additional'),
 ('additional', 'duty'),
 ('duty', 'legal'),
 ('legal', 'orientation'),
 ('orientation', 'program'),
 ('program', 'custodian'),
 ('custodian', 'lopc'),
 ('lopc', 'educates'),
 ('educates', 'custodian'),
 ('custodian', 'unaccompanied'),
 ('unaccompanied', 'child'),
 ('child', 'right'),
 ('right', 'immigration'),
 ('immigration', 'court'),
 ('court', 'process'),
 ('process', 'role'),
 ('role', 'data'),
 ('data', 'analyst'),
 ('analyst', 'report'),
 ('report', 'member'),
 ('member', 'research'),
 ('research', 'team'),
 ('team', 'work'),
 ('work', 'close'),
 ('close', 'collaboration'),
 ('collaboration', 'vera'),
 ('vera', 'staff'),
 ('staff', 'ongoing'),
 ('ongoing', 'database'),
 ('database', 'management'),
 ('management', 'monitoring'),
 ('monitoring', 'reporting'),
 ('reporting', 'analysis'),
 ('analysis', 'project'),
 ('project', 'youll'),
 ('youll', 'support'),
 ('support', 'team'),
 ('team', 'taking'),
 ('taking', 'ownership'),
 ('ownership', 'ongoing'),
 ('ongoing', 'monitoring'),
 ('monitoring', 'reporting'),
 ('reporting', 'task'),
 ('task', 'involving'),
 ('involving', 'large'),
 ('large', 'data'),
 ('data', 'set'),
 ('set', 'principal'),
 ('principal', 'responsibility'),
 ('responsibility', 'include'),
 ('include', 'supporting'),
 ('supporting', 'research'),
 ('research', 'staff'),
 ('staff', 'preparing'),
 ('preparing', 'large'),
 ('large', 'datasets'),
 ('datasets', 'analysis'),
 ('analysis', 'including'),
 ('including', 'merging'),
 ('merging', 'cleaning'),
 ('cleaning', 'recoding'),
 ('recoding', 'data'),
 ('data', 'providing'),
 ('providing', 'insight'),
 ('insight', 'program'),
 ('program', 'performance'),
 ('performance', 'summary'),
 ('summary', 'statistic'),
 ('statistic', 'performance'),
 ('performance', 'indicator'),
 ('indicator', 'producing'),
 ('producing', 'timely'),
 ('timely', 'report'),
 ('report', 'vera'),
 ('vera', 'project'),
 ('project', 'team'),
 ('team', 'member'),
 ('member', 'stakeholder'),
 ('stakeholder', 'improving'),
 ('improving', 'recurring'),
 ('recurring', 'reporting'),
 ('reporting', 'process'),
 ('process', 'optimizing'),
 ('optimizing', 'code'),
 ('code', 'producing'),
 ('producing', 'subsequent'),
 ('subsequent', 'documentation'),
 ('documentation', 'coordinating'),
 ('coordinating', 'database'),
 ('database', 'management'),
 ('management', 'task'),
 ('task', 'participating'),
 ('participating', 'new'),
 ('new', 'database'),
 ('database', 'design'),
 ('design', 'modifying'),
 ('modifying', 'existing'),
 ('existing', 'database'),
 ('database', 'communicating'),
 ('communicating', 'outside'),
 ('outside', 'engineer'),
 ('engineer', 'subcontractor'),
 ('subcontractor', 'developing'),
 ('developing', 'codebooks'),
 ('codebooks', 'delivering'),
 ('delivering', 'user'),
 ('user', 'training'),
 ('training', 'webinars'),
 ('webinars', 'database'),
 ('database', 'guide'),
 ('guide', 'building'),
 ('building', 'maintaining'),
 ('maintaining', 'interactive'),
 ('interactive', 'dashboard'),
 ('dashboard', 'documenting'),
 ('documenting', 'correcting'),
 ('correcting', 'data'),
 ('data', 'quality'),
 ('quality', 'issue'),
 ('issue', 'working'),
 ('working', 'supervisor'),
 ('supervisor', 'prioritize'),
 ('prioritize', 'program'),
 ('program', 'need'),
 ('need', 'assisting'),
 ('assisting', 'project'),
 ('project', 'task'),
 ('task', 'assigned'),
 ('assigned', 'youre'),
 ('youre', 'committed'),
 ('committed', 'improving'),
 ('improving', 'issue'),
 ('issue', 'affecting'),
 ('affecting', 'immigrant'),
 ('immigrant', 'united'),
 ('united', 'state'),
 ('state', 'applicant'),
 ('applicant', 'personal'),
 ('personal', 'experience'),
 ('experience', 'immigration'),
 ('immigration', 'system'),
 ('system', 'especially'),
 ('especially', 'encouraged'),
 ('encouraged', 'apply'),
 ('apply', 'youre'),
 ('youre', 'getting'),
 ('getting', 'started'),
 ('started', 'career'),
 ('career', '1'),
 ('1', '2'),
 ('2', 'year'),
 ('year', 'professional'),
 ('professional', 'internship'),
 ('internship', 'experience'),
 ('experience', 'working'),
 ('working', 'large'),
 ('large', 'datasets'),
 ('datasets', 'preparing'),
 ('preparing', 'data'),
 ('data', 'analysis'),
 ('analysis', 'real'),
 ('real', 'enthusiasm'),
 ('enthusiasm', 'working'),
 ('working', 'data'),
 ('data', 'comfortable'),
 ('comfortable', 'writing'),
 ('writing', 'query'),
 ('query', 'sql'),
 ('sql', 'r'),
 ('r', 'python'),
 ('python', 'solid'),
 ('solid', 'foundation'),
 ('foundation', 'coding'),
 ('coding', 'programming'),
 ('programming', 'language'),
 ('language', 'used'),
 ('used', 'manipulate'),
 ('manipulate', 'data'),
 ('data', 'experience'),
 ('experience', 'working'),
 ('working', 'collaboratively'),
 ('collaboratively', 'using'),
 ('using', 'tool'),
 ('tool', 'like'),
 ('like', 'git'),
 ('git', 'github'),
 ('github', 'plus'),
 ('plus', 'exceptional'),
 ('exceptional', 'attention'),
 ('attention', 'detail'),
 ('detail', 'strong'),
 ('strong', 'problem'),
 ('problem', 'solving'),
 ('solving', 'ability'),
 ('ability', 'logical'),
 ('logical', 'reasoning'),
 ('reasoning', 'skill'),
 ('skill', 'ability'),
 ('ability', 'detect'),
 ('detect', 'anomaly'),
 ('anomaly', 'data'),
 ('data', 'youre'),
 ('youre', 'able'),
 ('able', 'work'),
 ('work', 'multiple'),
 ('multiple', 'project'),
 ('project', 'effectively'),
 ('effectively', 'efficiently'),
 ('efficiently', 'independently'),
 ('independently', 'collaboratively'),
 ('collaboratively', 'team'),
 ('team', 'position'),
 ('position', 'involves'),
 ('involves', 'working'),
 ('working', 'secure'),
 ('secure', 'data'),
 ('data', 'may'),
 ('may', 'require'),
 ('require', 'government'),
 ('government', 'security'),
 ('security', 'clearance'),
 ('clearance', 'clearance'),
 ('clearance', 'restricted'),
 ('restricted', 'u'),
 ('u', 'citizen'),
 ('citizen', 'citizen'),
 ('citizen', 'country'),
 ('country', 'party'),
 ('party', 'collective'),
 ('collective', 'defense'),
 ('defense', 'agreement'),
 ('agreement', 'u'),
 ('u', 'list'),
 ('list', 'country'),
 ('country', 'detailed'),
 ('detailed', 'webpage'),
 ('webpage', 'additional'),
 ('additional', 'requirement'),
 ('requirement', 'clearance'),
 ('clearance', 'residence'),
 ('residence', 'united'),
 ('united', 'state'),
 ('state', 'least'),
 ('least', 'three'),
 ('three', 'last'),
 ('last', 'five'),
 ('five', 'year'),
 ('year', 'apply'),
 ('apply', 'please'),
 ('please', 'submit'),
 ('submit', 'cover'),
 ('cover', 'letter'),
 ('letter', 'resume'),
 ('resume', 'application'),
 ('application', 'considered'),
 ('considered', 'rolling'),
 ('rolling', 'basis'),
 ('basis', 'position'),
 ('position', 'filled'),
 ('filled', 'online'),
 ('online', 'submission'),
 ('submission', 'pdf'),
 ('pdf', 'format'),
 ('format', 'preferred'),
 ('preferred', 'application'),
 ('application', 'cover'),
 ('cover', 'letter'),
 ('letter', 'attached'),
 ('attached', 'considered'),
 ('considered', 'cover'),
 ('cover', 'letter'),
 ('letter', 'address'),
 ('address', 'interest'),
 ('interest', 'cij'),
 ('cij', 'position'),
 ('position', 'however'),
 ('however', 'necessary'),
 ('necessary', 'material'),
 ('material', 'may'),
 ('may', 'mailed'),
 ('mailed', 'faxed'),
 ('faxed', 'attn'),
 ('attn', 'human'),
 ('human', 'resource'),
 ('resource', 'cij'),
 ('cij', 'data'),
 ('data', 'analyst'),
 ('analyst', 'recruitment'),
 ('recruitment', 'vera'),
 ('vera', 'institute'),
 ('institute', 'justice'),
 ('justice', '34'),
 ('34', '35th'),
 ('35th', 'st'),
 ('st', 'suite'),
 ('suite', '4'),
 ('4', '2a'),
 ('2a', 'brooklyn'),
 ('brooklyn', 'ny'),
 ('ny', '11232'),
 ('11232', 'fax'),
 ('fax', '212'),
 ('212', '941'),
 ('941', '9407'),
 ('9407', 'please'),
 ('please', 'use'),
 ('use', 'one'),
 ('one', 'method'),
 ('method', 'online'),
 ('online', 'mail'),
 ('mail', 'fax'),
 ('fax', 'submission'),
 ('submission', 'phone'),
 ('phone', 'call'),
 ('call', 'please'),
 ('please', 'applicant'),
 ('applicant', 'selected'),
 ('selected', 'interview'),
 ('interview', 'contacted'),
 ('contacted', 'vera'),
 ('vera', 'equal'),
 ('equal', 'opportunity'),
 ('opportunity', 'affirmative'),
 ('affirmative', 'action'),
 ('action', 'employer'),
 ('employer', 'qualified'),
 ('qualified', 'applicant'),
 ('applicant', 'considered'),
 ('considered', 'employment'),
 ('employment', 'without'),
 ('without', 'unlawful'),
 ('unlawful', 'discrimination'),
 ('discrimination', 'based'),
 ('based', 'race'),
 ('race', 'color'),
 ('color', 'creed'),
 ('creed', 'national'),
 ('national', 'origin'),
 ('origin', 'sex'),
 ('sex', 'age'),
 ('age', 'disability'),
 ('disability', 'marital'),
 ('marital', 'status'),
 ('status', 'sexual'),
 ('sexual', 'orientation'),
 ('orientation', 'military'),
 ('military', 'status'),
 ('status', 'prior'),
 ('prior', 'record'),
 ('record', 'arrest'),
 ('arrest', 'conviction'),
 ('conviction', 'citizenship'),
 ('citizenship', 'status'),
 ('status', 'current'),
 ('current', 'employment'),
 ('employment', 'status'),
 ('status', 'caregiver'),
 ('caregiver', 'status'),
 ('status', 'vera'),
 ('vera', 'work'),
 ('work', 'advance'),
 ('advance', 'justice'),
 ('justice', 'particularly'),
 ('particularly', 'racial'),
 ('racial', 'justice'),
 ('justice', 'increasingly'),
 ('increasingly', 'multicultural'),
 ('multicultural', 'country'),
 ('country', 'globally'),
 ('globally', 'connected'),
 ('connected', 'world'),
 ('world', 'value'),
 ('value', 'diverse'),
 ('diverse', 'experience'),
 ('experience', 'including'),
 ('including', 'regard'),
 ('regard', 'educational'),
 ('educational', 'background'),
 ('background', 'justice'),
 ('justice', 'system'),
 ('system', 'contact'),
 ('contact', 'depend'),
 ('depend', 'diverse'),
 ('diverse', 'staff'),
 ('staff', 'carry'),
 ('carry', 'mission'),
 ('mission', 'information'),
 ('information', 'vera'),
 ('vera', 'cijs'),
 ('cijs', 'work'),
 ('work', 'please'),
 ('please', 'visit'),
 ('visit', 'wwwveraorg'),
 ('wwwveraorg', 'powered'),
 ('powered', 'jazzhr')]

In [19]:
# master_df = pd.Series(nltk.ngrams(master_df['two_word_description'], 2))
# ('data', 'mining') in master_df['two_word_apply'][1033]

# master_df.filter(items='data')
# master_df['two_word_apply'][master_df['two_word_apply'].isin([("data", "mining")])]
master_df['job_experience'] = master_df.job_experience.apply(lambda x: [' '.join(t) for t in x])
master_df['job_experience']

0       [eager roll, roll sleeve, sleeve harness, harn...
1       [overview provides, provides analytical, analy...
2       [looking senior, senior data, data analyst, an...
3       [requisition numberrr, numberrr 0001939, 00019...
4       [fanduel group, group fanduel, fanduel group, ...
                              ...
8127    [edward jones, jones help, help client, client...
8128    [summary meta, meta platform, platform inc, in...
8129    [description koch, koch industry, industry mis...
8130    [2023 internship, internship associate, associ...
8131    [staffigo business, business providing, provid...
Name: job_experience, Length: 8132, dtype: object

In [23]:
s = master_df['job_experience'].apply(lambda x: ("2", "years") in x)
s

0       False
1       False
2       False
3       False
4       False
        ...
8127    False
8128    False
8129    False
8130    False
8131    False
Name: job_experience, Length: 8132, dtype: bool

In [20]:
experience = ["1 years", "2 years", "3 years", "4 years", "5 years", "6 years", "7 years", "0-1 years","1-2 years", "1-3 years" , "1-4 years",
                "1-5 years", "1-6 years", "2-3 years", "2-4 years", "2-5 years", "2-6 years", "3-4 years", "3-5 years", "1+ years", "2+ years", "3+ years",
                "4+ years", "5+ years", "6+ years"]

In [21]:
master_df['job_experience'] = master_df['job_experience'].apply(lambda x: [item for item in x if item in experience])

In [22]:
master_df['job_experience'].head(50)

0     []
1     []
2     []
3     []
4     []
5     []
6     []
7     []
8     []
9     []
10    []
11    []
12    []
13    []
14    []
15    []
16    []
17    []
18    []
19    []
20    []
21    []
22    []
23    []
24    []
25    []
26    []
27    []
28    []
29    []
30    []
31    []
32    []
33    []
34    []
35    []
36    []
37    []
38    []
39    []
40    []
41    []
42    []
43    []
44    []
45    []
46    []
47    []
48    []
49    []
Name: job_experience, dtype: object