In [1]:
# Make a data directory and copy .env and functions.py

datadir = 'data/'
# !mkdir {datadir}
# !cp ../repositories/da-external-data-sourcing/sql_functions.py . 
# !cp ../repositories/da-external-data-sourcing/.env .

In [2]:
import pandas as pd

In [3]:
analyst_df = pd.read_csv('dataset/DataAnalyst.csv')
scientist_df = pd.read_csv('dataset/DataScientist.csv')
jobs_df = pd.read_csv('dataset/gsearch_jobs 3.csv')

In [4]:
display(analyst_df.info())
display(scientist_df.info())
display(jobs_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2253 non-null   int64
 1   Job Title          2253 non-null   object
 2   Salary Estimate    2253 non-null   object
 3   Job Description    2253 non-null   object
 4   Rating             2253 non-null   float64
 5   Company Name       2252 non-null   object
 6   Location           2253 non-null   object
 7   Headquarters       2253 non-null   object
 8   Size               2253 non-null   object
 9   Founded            2253 non-null   int64
 10  Type of ownership  2253 non-null   object
 11  Industry           2253 non-null   object
 12  Sector             2253 non-null   object
 13  Revenue            2253 non-null   object
 14  Competitors        2253 non-null   object
 15  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 281.8+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3909 entries, 0 to 3908
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3909 non-null   int64
 1   index              3909 non-null   int64
 2   Job Title          3909 non-null   object
 3   Salary Estimate    3909 non-null   object
 4   Job Description    3909 non-null   object
 5   Rating             3909 non-null   float64
 6   Company Name       3909 non-null   object
 7   Location           3909 non-null   object
 8   Headquarters       3909 non-null   object
 9   Size               3909 non-null   object
 10  Founded            3909 non-null   int64
 11  Type of ownership  3909 non-null   object
 12  Industry           3909 non-null   object
 13  Sector             3909 non-null   object
 14  Revenue            3909 non-null   object
 15  Competitors        3909 non-null   object
 16  Easy Apply         3909 non-null   object
dtypes: float64(1), int64(3), object(13)
memory usage: 519.3+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1970 entries, 0 to 1969
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1970 non-null   int64
 1   index                1970 non-null   int64
 2   title                1970 non-null   object
 3   company_name         1970 non-null   object
 4   location             1967 non-null   object
 5   via                  1970 non-null   object
 6   description          1970 non-null   object
 7   extensions           1970 non-null   object
 8   job_id               1970 non-null   object
 9   thumbnail            1126 non-null   object
 10  posted_at            1970 non-null   object
 11  schedule_type        1961 non-null   object
 12  work_from_home       993 non-null    object
 13  salary               382 non-null    object
 14  search_term          1970 non-null   object
 15  date_time            1970 non-null   object
 16  search_location      1970 non-null   object
 17  commute_time         0 non-null      float64
 18  salary_pay           382 non-null    object
 19  salary_rate          382 non-null    object
 20  salary_avg           382 non-null    float64
 21  salary_min           342 non-null    float64
 22  salary_max           342 non-null    float64
 23  salary_hourly        214 non-null    float64
 24  salary_yearly        166 non-null    float64
 25  salary_standardized  382 non-null    float64
 26  description_tokens   1970 non-null   object
dtypes: float64(7), int64(2), object(18)
memory usage: 415.7+ KB

None

In [5]:
#Rename Columns to lower and replace white spaces with Underscore
analyst_df.rename(columns=lambda x : x.lower(), inplace=True)
analyst_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
scientist_df.rename(columns=lambda x : x.lower(), inplace=True)
scientist_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
jobs_df.rename(columns=lambda x : x.lower(), inplace=True)
jobs_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)

jobs_df.rename(columns= {'title':'job_title', 'description':'job_description', 'description':'job_description'}, inplace=True)

In [6]:
data_analyst_df2 = analyst_df[['job_title', 'job_description']].copy()
data_scientist_df2 = scientist_df[['job_title', 'job_description']].copy()
google_job_df2 = jobs_df[['job_title', 'job_description']].copy()

In [7]:
#Join Data Analyst Dataset and Data Scientist Dataset
analyst_scientist_df = pd.concat([data_analyst_df2, data_scientist_df2], ignore_index=True)

In [8]:
#lets rename columns of the google job dataset
# google_job_df2 = google_job_df2.rename(columns={'title': 'job_title', 'description': 'job_description'})

In [9]:
#join google dataset to the data analyst /scientist dataset
master_df = pd.concat([analyst_scientist_df, google_job_df2],ignore_index=True)

In [10]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8132 entries, 0 to 8131
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        8132 non-null   object
 1   job_description  8132 non-null   object
dtypes: object(2)
memory usage: 127.2+ KB

In [11]:
import string
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

In [12]:
analyst_df["job_description"] = analyst_df["job_description"].str.replace("\n", " ")

In [13]:
master_df['job_description'] = master_df['job_description'].replace({'/':' ','-':' '},regex=True)

In [14]:
# Import Libraries
import string # a collection of string constraints: white-space, punctuation, etc.
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
#nltk.download('punkt')   # Required for tokenization
#nltk.download('wordnet') # Required for lemmatization
# nltk.download('popular')
from nltk.corpus import stopwords
# Instantiate
lemmatizer = WordNetLemmatizer()
# Create our own stop words
stop_words = (                                        \
    "\n ’ sleeves company and of for in to a or years l   \
    other were that to drive policy we at with our   \
    firm follows under consolidated have these over   \
    include billion million december which an le from \
    certain le — million had show apple including     \
    as noncurrent current total three are on not is   \
    involving millions shows centers contains      "  \
             ).split()
# Exclusion list of punctuations and numbers
# exclist = string.punctuation + string.digits # Do we also need digits?
exclude_punctuation = "!$%&'()*,-./:;<=>?@[\]^_`{|}~"
exclist = exclude_punctuation + string.digits # Do we also need digits?
# Print the exclusion list
print(exclist)

!$%&'()*,-./:;<=>?@[\]^_`{|}~0123456789

In [15]:
# Create a Function
def clean_texts(text):
    """ Function to perform preprocessing """
    
    # Convert to lower cases
    text = text.lower()
    
    # Remove punctuations and numbers
    text = text.translate(str.maketrans("", "", exclude_punctuation))
    
    # White space before and after punctuation?
    # text = text.translate(str.maketrans({key: " {0} ".format(key) for key in string.punctuation}))
    
    
    # Tokenization
    tokens = word_tokenize(text)
        
    # Lemmatization
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Remove stop words
    stopwords = nltk.corpus.stopwords.words('english')
    tokens = [token for token in tokens if token not in stopwords]
    
    # Join tokens
    clean_text = " ".join(tokens)
    
    # Return the output
    return clean_text
# Apply the function to all disclosures
master_df['clean_description'] = master_df['job_description'].apply(clean_texts)
# View the first 5 rows
master_df.head()

,job_title,job_description,clean_description
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...

In [16]:
# natural language processing: n-gram ranking
import re
import unicodedata
# import nltk
# from nltk.corpus import stopwords# add appropriate words that will be ignored in the analysis
# ADDITIONAL_STOPWORDS = ['covfefe']
import matplotlib.pyplot as plt

def basic_clean(text):
  """
  A simple function to clean up the data. All the words that
  are not designated as a stop word is then lemmatized after
  encoding and basic regex parsing are performed.
  """
  wnl = nltk.stem.WordNetLemmatizer()
  stopwords = nltk.corpus.stopwords.words('english') # + ADDITIONAL_STOPWORDS
  text = (unicodedata.normalize('NFKD', text)
    .encode('ascii', 'ignore')
    .decode('utf-8', 'ignore')
    .lower())
  words = re.sub(r'[^\w\s]', '', text).split()
  return [wnl.lemmatize(word) for word in words if word not in stopwords]
master_df['description_two_words'] = master_df['job_description'].apply(basic_clean)
# master_df['two_word_description'] = pd.Series(nltk.ngrams(master_df['two_word_description'], 2))
# master_df['two_word_description'] = master_df['job_description'].apply(nltk.ngrams(master_df), 2)
master_df.head()

,job_title,job_description,clean_description,description_two_words
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...,"[eager, roll, sleeve, harness, data, drive, po..."
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...,"[overview, provides, analytical, technical, su..."
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...,"[looking, senior, data, analyst, love, mentors..."
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...,"[requisition, numberrr, 0001939, remoteyes, co..."
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...,"[fanduel, group, fanduel, group, world, class,..."

In [17]:
# words = basic_clean(''.join(str(df['text'].tolist())))

In [18]:
# master_df['two_description_words'] = word_tokenize(master_df['clean_description'], 2)
# master_df['two_description_words']

In [19]:
master_df['description_two_words'] = master_df["description_two_words"].apply(lambda x:list(nltk.ngrams(x, n=2)))

In [20]:
master_df['description_two_words'][1033]

[('discount', 'tire'),
 ('tire', 'celebrate'),
 ('celebrate', 'spirit'),
 ('spirit', 'people'),
 ('people', 'extraordinary'),
 ('extraordinary', 'pride'),
 ('pride', 'enthusiasm'),
 ('enthusiasm', 'america'),
 ('america', 'largest'),
 ('largest', 'independent'),
 ('independent', 'tire'),
 ('tire', 'retailer'),
 ('retailer', 'specializing'),
 ('specializing', 'tire'),
 ('tire', 'wheel'),
 ('wheel', '1000'),
 ('1000', 'store'),
 ('store', 'location'),
 ('location', 'continue'),
 ('continue', 'grow'),
 ('grow', 'every'),
 ('every', 'year'),
 ('year', 'consistent'),
 ('consistent', 'growth'),
 ('growth', 'last'),
 ('last', '60'),
 ('60', 'year'),
 ('year', 'loyalty'),
 ('loyalty', 'customer'),
 ('customer', 'passion'),
 ('passion', 'people'),
 ('people', 'make'),
 ('make', 'discount'),
 ('discount', 'tire'),
 ('tire', 'great'),
 ('great', 'place'),
 ('place', 'workeven'),
 ('workeven', 'exciting'),
 ('exciting', 'discount'),
 ('discount', 'tire'),
 ('tire', 'predicting'),
 ('predicting', 'embracing'),
 ('embracing', 'driving'),
 ('driving', 'change'),
 ('change', 'expected'),
 ('expected', 'automotive'),
 ('automotive', 'industry'),
 ('industry', 'particular'),
 ('particular', 'data'),
 ('data', 'analytics'),
 ('analytics', 'seen'),
 ('seen', 'competitive'),
 ('competitive', 'advantage'),
 ('advantage', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'central'),
 ('central', 'helping'),
 ('helping', 'company'),
 ('company', 'executive'),
 ('executive', 'address'),
 ('address', 'short'),
 ('short', 'term'),
 ('term', 'long'),
 ('long', 'term'),
 ('term', 'opportunity'),
 ('opportunity', 'support'),
 ('support', 'strategic'),
 ('strategic', 'data'),
 ('data', 'oriented'),
 ('oriented', 'actionable'),
 ('actionable', 'insight'),
 ('insight', 'solution'),
 ('solution', 'related'),
 ('related', 'discount'),
 ('discount', 'tire'),
 ('tire', 'complex'),
 ('complex', 'business'),
 ('business', 'involving'),
 ('involving', 'large'),
 ('large', 'number'),
 ('number', 'people'),
 ('people', 'property'),
 ('property', 'digital'),
 ('digital', 'asset'),
 ('asset', 'sell'),
 ('sell', 'tire'),
 ('tire', 'wheel'),
 ('wheel', 'around'),
 ('around', 'world'),
 ('world', 'million'),
 ('million', 'customer'),
 ('customer', 'store'),
 ('store', 'website'),
 ('website', 'unlike'),
 ('unlike', 'traditional'),
 ('traditional', 'retail'),
 ('retail', 'customer'),
 ('customer', 'expect'),
 ('expect', 'u'),
 ('u', 'simply'),
 ('simply', 'sell'),
 ('sell', 'tire'),
 ('tire', 'wheel'),
 ('wheel', 'service'),
 ('service', 'vehicle'),
 ('vehicle', 'making'),
 ('making', 'even'),
 ('even', 'interesting'),
 ('interesting', 'complex'),
 ('complex', 'analytics'),
 ('analytics', 'challenge'),
 ('challenge', 'additionally'),
 ('additionally', 'collaborate'),
 ('collaborate', 'multi'),
 ('multi', 'disciplinary'),
 ('disciplinary', 'team'),
 ('team', 'solution'),
 ('solution', 'architect'),
 ('architect', 'engineer'),
 ('engineer', 'data'),
 ('data', 'scientist'),
 ('scientist', 'wide'),
 ('wide', 'range'),
 ('range', 'business'),
 ('business', 'problem'),
 ('problem', 'business'),
 ('business', 'group'),
 ('group', 'supported'),
 ('supported', 'include'),
 ('include', 'limited'),
 ('limited', 'store'),
 ('store', 'operation'),
 ('operation', 'real'),
 ('real', 'estate'),
 ('estate', 'finance'),
 ('finance', 'role'),
 ('role', 'actively'),
 ('actively', 'involved'),
 ('involved', 'shaping'),
 ('shaping', 'company'),
 ('company', 'strategy'),
 ('strategy', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'collaborate'),
 ('collaborate', 'large'),
 ('large', 'multi'),
 ('multi', 'disciplinary'),
 ('disciplinary', 'team'),
 ('team', 'data'),
 ('data', 'engineer'),
 ('engineer', 'data'),
 ('data', 'analyst'),
 ('analyst', 'data'),
 ('data', 'scientist'),
 ('scientist', 'wide'),
 ('wide', 'range'),
 ('range', 'business'),
 ('business', 'problem'),
 ('problem', 'work'),
 ('work', 'multiple'),
 ('multiple', 'project'),
 ('project', 'provide'),
 ('provide', 'value'),
 ('value', 'customer'),
 ('customer', 'also'),
 ('also', 'routinely'),
 ('routinely', 'involved'),
 ('involved', 'helping'),
 ('helping', 'building'),
 ('building', 'internal'),
 ('internal', 'capability'),
 ('capability', 'edge'),
 ('edge', 'analytics'),
 ('analytics', 'industry'),
 ('industry', 'work'),
 ('work', 'providing'),
 ('providing', 'solution'),
 ('solution', 'wide'),
 ('wide', 'range'),
 ('range', 'internal'),
 ('internal', 'customer'),
 ('customer', 'across'),
 ('across', 'organization'),
 ('organization', 'including'),
 ('including', 'senior'),
 ('senior', 'executive'),
 ('executive', 'middle'),
 ('middle', 'management'),
 ('management', 'coming'),
 ('coming', 'various'),
 ('various', 'domain'),
 ('domain', 'including'),
 ('including', 'limited'),
 ('limited', 'retail'),
 ('retail', 'manufacturing'),
 ('manufacturing', 'store'),
 ('store', 'operation'),
 ('operation', 'automotive'),
 ('automotive', 'real'),
 ('real', 'estate'),
 ('estate', 'service'),
 ('service', 'essential'),
 ('essential', 'duty'),
 ('duty', 'responsibility'),
 ('responsibility', 'work'),
 ('work', 'large'),
 ('large', 'complex'),
 ('complex', 'data'),
 ('data', 'set'),
 ('set', 'solve'),
 ('solve', 'difficult'),
 ('difficult', 'non'),
 ('non', 'routine'),
 ('routine', 'analysis'),
 ('analysis', 'problem'),
 ('problem', 'applying'),
 ('applying', 'advanced'),
 ('advanced', 'analytical'),
 ('analytical', 'method'),
 ('method', 'needed'),
 ('needed', 'conduct'),
 ('conduct', 'end'),
 ('end', 'end'),
 ('end', 'analysis'),
 ('analysis', 'includes'),
 ('includes', 'data'),
 ('data', 'gathering'),
 ('gathering', 'requirement'),
 ('requirement', 'specification'),
 ('specification', 'processing'),
 ('processing', 'analysis'),
 ('analysis', 'ongoing'),
 ('ongoing', 'deliverable'),
 ('deliverable', 'presentation'),
 ('presentation', 'work'),
 ('work', 'advanced'),
 ('advanced', 'analytics'),
 ('analytics', 'area'),
 ('area', 'like'),
 ('like', 'deep'),
 ('deep', 'learning'),
 ('learning', 'complex'),
 ('complex', 'statistical'),
 ('statistical', 'data'),
 ('data', 'analysis'),
 ('analysis', 'interaction'),
 ('interaction', 'team'),
 ('team', 'stakeholder'),
 ('stakeholder', 'person'),
 ('person', 'meeting'),
 ('meeting', 'towards'),
 ('towards', 'making'),
 ('making', 'business'),
 ('business', 'recommendation'),
 ('recommendation', 'based'),
 ('based', 'data'),
 ('data', 'effective'),
 ('effective', 'presentation'),
 ('presentation', 'finding'),
 ('finding', 'visual'),
 ('visual', 'display'),
 ('display', 'quantitative'),
 ('quantitative', 'information'),
 ('information', 'develop'),
 ('develop', 'analysis'),
 ('analysis', 'forecasting'),
 ('forecasting', 'optimization'),
 ('optimization', 'method'),
 ('method', 'model'),
 ('model', 'provide'),
 ('provide', 'business'),
 ('business', 'insight'),
 ('insight', 'solution'),
 ('solution', 'key'),
 ('key', 'stakeholder'),
 ('stakeholder', 'applies'),
 ('applies', 'methodology'),
 ('methodology', 'future'),
 ('future', 'strategic'),
 ('strategic', 'decision'),
 ('decision', 'including'),
 ('including', 'limited'),
 ('limited', 'store'),
 ('store', 'operation'),
 ('operation', 'finance'),
 ('finance', 'human'),
 ('human', 'capital'),
 ('capital', 'management'),
 ('management', 'oversees'),
 ('oversees', 'activity'),
 ('activity', 'junior'),
 ('junior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'oversees'),
 ('oversees', 'conduct'),
 ('conduct', 'conversion'),
 ('conversion', 'data'),
 ('data', 'insight'),
 ('insight', 'lead'),
 ('lead', 'informed'),
 ('informed', 'business'),
 ('business', 'decision'),
 ('decision', 'work'),
 ('work', 'directly'),
 ('directly', 'stakeholder'),
 ('stakeholder', 'business'),
 ('business', 'top'),
 ('top', 'management'),
 ('management', 'executive'),
 ('executive', 'within'),
 ('within', 'assigned'),
 ('assigned', 'department'),
 ('department', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'handle'),
 ('handle', 'multiple'),
 ('multiple', 'simultaneous'),
 ('simultaneous', 'task'),
 ('task', 'prioritize'),
 ('prioritize', 'work'),
 ('work', 'remain'),
 ('remain', 'functional'),
 ('functional', 'pressure'),
 ('pressure', 'aggressive'),
 ('aggressive', 'timeline'),
 ('timeline', 'required'),
 ('required', 'qualification'),
 ('qualification', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'experience'),
 ('experience', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'position'),
 ('position', 'advanced'),
 ('advanced', 'data'),
 ('data', 'role'),
 ('role', 'requires'),
 ('requires', 'extensive'),
 ('extensive', 'experience'),
 ('experience', 'minimum'),
 ('minimum', '5'),
 ('5', 'year'),
 ('year', 'industry'),
 ('industry', 'experience'),
 ('experience', 'business'),
 ('business', 'data'),
 ('data', 'analyst'),
 ('analyst', '3'),
 ('3', '5'),
 ('5', 'experience'),
 ('experience', 'data'),
 ('data', 'analysis'),
 ('analysis', 'using'),
 ('using', 'tool'),
 ('tool', 'sql'),
 ('sql', 'preferably'),
 ('preferably', 'work'),
 ('work', 'fast'),
 ('fast', 'pace'),
 ('pace', 'dynamic'),
 ('dynamic', 'business'),
 ('business', 'setting'),
 ('setting', 'individual'),
 ('individual', 'experience'),
 ('experience', 'working'),
 ('working', 'report'),
 ('report', 'creation'),
 ('creation', 'modeling'),
 ('modeling', 'trend'),
 ('trend', 'forecasting'),
 ('forecasting', 'understanding'),
 ('understanding', 'scripting'),
 ('scripting', 'experience'),
 ('experience', 'python'),
 ('python', 'perl'),
 ('perl', 'javascript'),
 ('javascript', 'shell'),
 ('shell', 'practical'),
 ('practical', 'knowledge'),
 ('knowledge', 'data'),
 ('data', 'various'),
 ('various', 'form'),
 ('form', 'data'),
 ('data', 'warehouse'),
 ('warehouse', 'sql'),
 ('sql', 'unstructured'),
 ('unstructured', 'data'),
 ('data', 'environment'),
 ('environment', 'pig'),
 ('pig', 'hive'),
 ('hive', 'impala'),
 ('impala', 'strong'),
 ('strong', 'working'),
 ('working', 'knowledge'),
 ('knowledge', 'bi'),
 ('bi', 'reporting'),
 ('reporting', 'tool'),
 ('tool', 'ie'),
 ('ie', 'tableau'),
 ('tableau', 'business'),
 ('business', 'object'),
 ('object', 'microstrategy'),
 ('microstrategy', 'preferred'),
 ('preferred', 'data'),
 ('data', 'visualization'),
 ('visualization', 'tool'),
 ('tool', 'proficient'),
 ('proficient', 'using'),
 ('using', 'm'),
 ('m', 'word'),
 ('word', 'm'),
 ('m', 'excel'),
 ('excel', 'powerpoint'),
 ('powerpoint', 'necessary'),
 ('necessary', 'creation'),
 ('creation', 'visually'),
 ('visually', 'verbally'),
 ('verbally', 'engaging'),
 ('engaging', 'report'),
 ('report', 'various'),
 ('various', 'assigned'),
 ('assigned', 'departmental'),
 ('departmental', 'head'),
 ('head', 'management'),
 ('management', 'stakeholder'),
 ('stakeholder', 'including'),
 ('including', 'senior'),
 ('senior', 'executive'),
 ('executive', 'demonstrated'),
 ('demonstrated', 'knowledge'),
 ('knowledge', 'data'),
 ('data', 'governance'),
 ('governance', 'data'),
 ('data', 'quality'),
 ('quality', 'management'),
 ('management', 'concept'),
 ('concept', 'data'),
 ('data', 'quality'),
 ('quality', 'tool'),
 ('tool', 'ie'),
 ('ie', 'informatica'),
 ('informatica', 'dq'),
 ('dq', 'understanding'),
 ('understanding', 'agile'),
 ('agile', 'development'),
 ('development', 'methodology'),
 ('methodology', 'software'),
 ('software', 'design'),
 ('design', 'pattern'),
 ('pattern', 'network'),
 ('network', 'design'),
 ('design', 'architecture'),
 ('architecture', 'experience'),
 ('experience', 'quantitative'),
 ('quantitative', 'analysis'),
 ('analysis', 'statistical'),
 ('statistical', 'modelling'),
 ('modelling', 'clear'),
 ('clear', 'understanding'),
 ('understanding', 'key'),
 ('key', 'reporting'),
 ('reporting', 'analytics'),
 ('analytics', 'general'),
 ('general', 'ledger'),
 ('ledger', 'management'),
 ('management', 'data'),
 ('data', 'warehousing'),
 ('warehousing', 'needed'),
 ('needed', 'role'),
 ('role', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'involves'),
 ('involves', 'working'),
 ('working', 'people'),
 ('people', 'communication'),
 ('communication', 'skill'),
 ('skill', 'excellent'),
 ('excellent', 'verbal'),
 ('verbal', 'written'),
 ('written', 'presentation'),
 ('presentation', 'communication'),
 ('communication', 'skill'),
 ('skill', 'senior'),
 ('senior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'need'),
 ('need', 'communication'),
 ('communication', 'skill'),
 ('skill', 'collaborating'),
 ('collaborating', 'peer'),
 ('peer', 'stakeholder'),
 ('stakeholder', 'business'),
 ('business', 'acumen'),
 ('acumen', 'essential'),
 ('essential', 'analytical'),
 ('analytical', 'skill'),
 ('skill', 'candidate'),
 ('candidate', 'position'),
 ('position', 'must'),
 ('must', 'demonstrate'),
 ('demonstrate', 'deep'),
 ('deep', 'interest'),
 ('interest', 'research'),
 ('research', 'data'),
 ('data', 'analysis'),
 ('analysis', 'drawing'),
 ('drawing', 'actionable'),
 ('actionable', 'insight'),
 ('insight', 'form'),
 ('form', 'raw'),
 ('raw', 'data'),
 ('data', 'information'),
 ('information', 'help'),
 ('help', 'business'),
 ('business', 'cause'),
 ('cause', 'candidate'),
 ('candidate', 'skilled'),
 ('skilled', 'statistical'),
 ('statistical', 'econometric'),
 ('econometric', 'modeling'),
 ('modeling', 'performing'),
 ('performing', 'quantitative'),
 ('quantitative', 'analysis'),
 ('analysis', 'technological'),
 ('technological', 'data'),
 ('data', 'mining'),
 ('mining', 'analysis'),
 ('analysis', 'technique'),
 ('technique', 'interpersonal'),
 ('interpersonal', 'skill'),
 ('skill', 'candidate'),
 ('candidate', 'must'),
 ('must', 'posse'),
 ('posse', 'certain'),
 ('certain', 'personal'),
 ('personal', 'trait'),
 ('trait', 'make'),
 ('make', 'even'),
 ('even', 'suited'),
 ('suited', 'role'),
 ('role', 'candidate'),
 ('candidate', 'entrepreneurial'),
 ('entrepreneurial', 'mindset'),
 ('mindset', 'willing'),
 ('willing', 'accountable'),
 ('accountable', 'business'),
 ('business', 'performance'),
 ('performance', 'exceptional'),
 ('exceptional', 'attention'),
 ('attention', 'detail'),
 ('detail', 'ability'),
 ('ability', 'handle'),
 ('handle', 'multiple'),
 ('multiple', 'task'),
 ('task', 'meet'),
 ('meet', 'tight'),
 ('tight', 'deadline'),
 ('deadline', 'creative'),
 ('creative', 'innovative'),
 ('innovative', 'problem'),
 ('problem', 'solving'),
 ('solving', 'skill'),
 ('skill', 'self'),
 ('self', 'motivated'),
 ('motivated', 'proactive'),
 ('proactive', 'demonstrate'),
 ('demonstrate', 'calmness'),
 ('calmness', 'time'),
 ('time', 'uncertainty'),
 ('uncertainty', 'stress'),
 ('stress', 'people'),
 ('people', 'skill'),
 ('skill', 'interactive'),
 ('interactive', 'role'),
 ('role', 'effectively'),
 ('effectively', 'execute'),
 ('execute', 'duty'),
 ('duty', 'must'),
 ('must', 'natural'),
 ('natural', 'ability'),
 ('ability', 'get'),
 ('get', 'along'),
 ('along', 'people'),
 ('people', 'establish'),
 ('establish', 'strong'),
 ('strong', 'meaningful'),
 ('meaningful', 'relationship'),
 ('relationship', 'others'),
 ('others', 'guarantee'),
 ('guarantee', 'collaborative'),
 ('collaborative', 'personnel'),
 ('personnel', 'departmental'),
 ('departmental', 'head'),
 ('head', 'management'),
 ('management', 'key'),
 ('key', 'stakeholder'),
 ('stakeholder', 'gain'),
 ('gain', 'trust'),
 ('trust', 'ability'),
 ('ability', 'junior'),
 ('junior', 'data'),
 ('data', 'analyst'),
 ('analyst', 'personnel'),
 ('personnel', 'readily'),
 ('readily', 'follow'),
 ('follow', 'directive'),
 ('directive', 'trust'),
 ('trust', 'judgment'),
 ('judgment', 'insight'),
 ('insight', 'specialized'),
 ('specialized', 'knowledge'),
 ('knowledge', 'skill'),
 ('skill', 'ability'),
 ('ability', 'advanced'),
 ('advanced', 'experience'),
 ('experience', 'statistical'),
 ('statistical', 'software'),
 ('software', 'eg'),
 ('eg', 'r'),
 ('r', 'python'),
 ('python', 'database'),
 ('database', 'language'),
 ('language', 'eg'),
 ('eg', 'sql'),
 ('sql', 'advanced'),
 ('advanced', 'experience'),
 ('experience', 'articulating'),
 ('articulating', 'business'),
 ('business', 'question'),
 ('question', 'using'),
 ('using', 'mathematical'),
 ('mathematical', 'technique'),
 ('technique', 'arrive'),
 ('arrive', 'answer'),
 ('answer', 'using'),
 ('using', 'available'),
 ('available', 'data'),
 ('data', 'experience'),
 ('experience', 'translating'),
 ('translating', 'analysis'),
 ('analysis', 'result'),
 ('result', 'business'),
 ('business', 'recommendation'),
 ('recommendation', 'demonstrated'),
 ('demonstrated', 'skill'),
 ('skill', 'selecting'),
 ('selecting', 'right'),
 ('right', 'statistical'),
 ('statistical', 'tool'),
 ('tool', 'given'),
 ('given', 'data'),
 ('data', 'analysis'),
 ('analysis', 'problem'),
 ('problem', 'demonstrated'),
 ('demonstrated', 'leadership'),
 ('leadership', 'self'),
 ('self', 'direction'),
 ('direction', 'demonstrated'),
 ('demonstrated', 'willingness'),
 ('willingness', 'teach'),
 ('teach', 'others'),
 ('others', 'learn'),
 ('learn', 'new'),
 ('new', 'technique'),
 ('technique', 'experience'),
 ('experience', 'ai'),
 ('ai', 'deep'),
 ('deep', 'learning'),
 ('learning', 'text'),
 ('text', 'image'),
 ('image', 'video'),
 ('video', 'analytics'),
 ('analytics', 'preferred'),
 ('preferred', 'experience'),
 ('experience', 'cloud'),
 ('cloud', 'computing'),
 ('computing', 'data'),
 ('data', 'streaming'),
 ('streaming', 'preferred'),
 ('preferred', 'sql'),
 ('sql', 'relational'),
 ('relational', 'database'),
 ('database', 'knowledge'),
 ('knowledge', 'required'),
 ('required', 'educational'),
 ('educational', 'requirement'),
 ('requirement', 'master'),
 ('master', 'degree'),
 ('degree', 'quantitative'),
 ('quantitative', 'discipline'),
 ('discipline', 'eg'),
 ('eg', 'analytics'),
 ('analytics', 'statistic'),
 ('statistic', 'computer'),
 ('computer', 'science'),
 ('science', 'data'),
 ('data', 'science'),
 ('science', 'economics'),
 ('economics', 'mathematics'),
 ('mathematics', 'physic'),
 ('physic', 'electrical'),
 ('electrical', 'engineering'),
 ('engineering', 'industrial'),
 ('industrial', 'engineering'),
 ('engineering', 'stem'),
 ('stem', 'field'),
 ('field', 'work'),
 ('work', 'day'),
 ('day', 'normal'),
 ('normal', 'work'),
 ('work', 'day'),
 ('day', 'monday'),
 ('monday', 'friday'),
 ('friday', 'occasional'),
 ('occasional', 'saturday'),
 ('saturday', 'sunday'),
 ('sunday', 'may'),
 ('may', 'necessary'),
 ('necessary', 'work'),
 ('work', 'hour'),
 ('hour', 'normal'),
 ('normal', 'work'),
 ('work', 'hour'),
 ('hour', '800'),
 ('800', '500'),
 ('500', 'pm'),
 ('pm', 'additional'),
 ('additional', 'hour'),
 ('hour', 'may'),
 ('may', 'necessary'),
 ('necessary', 'job'),
 ('job', 'requirement')]

In [21]:
# master_df = pd.Series(nltk.ngrams(master_df['two_word_description'], 2))
# ('data', 'mining') in master_df['two_word_apply'][1033]
s = master_df['description_two_words'].apply(lambda x: ("data", "mining") in x)
# s
# master_df.filter(items='data')
# master_df['two_word_apply'][master_df['two_word_apply'].isin([("data", "mining")])]
master_df['description_two_words'] = master_df.description_two_words.apply(lambda x: [' '.join(t) for t in x])
master_df['description_two_words']

0       [eager roll, roll sleeve, sleeve harness, harn...
1       [overview provides, provides analytical, analy...
2       [looking senior, senior data, data analyst, an...
3       [requisition numberrr, numberrr 0001939, 00019...
4       [fanduel group, group fanduel, fanduel group, ...
                              ...
8127    [edward jones, jones help, help client, client...
8128    [summary meta, meta platform, platform inc, in...
8129    [description koch, koch industry, industry mis...
8130    [2023 internship, internship associate, associ...
8131    [staffigo business, business providing, provid...
Name: description_two_words, Length: 8132, dtype: object

In [22]:
# Tried to follow https://realpython.com/nltk-nlp-python/ for using NLTK
nltk.download("stopwords")
from nltk.corpus import stopwords 
from nltk import FreqDist

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/georgeyordel/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
# filtered_list = []

# for word in zero_text:
#     if word.casefold() not in stop_words:
#         filtered_list.append(word)

In [24]:
# from nltk import ngrams
# resume = '... working in the data science field for years ...'
# n = 2
# bigrams = ngrams(resume.split(), n)
# for grams in bigrams:
#   print grams

In [25]:
master_df['description_words'] = master_df["clean_description"].apply(word_tokenize)

In [26]:
# master_df['description_words'] = master_df["job_description"].apply(word_tokenize)

In [27]:
# master_df['description_words'][0]

In [28]:
# master_df['description_words'] = master_df['description_words'].apply(lambda x: [item for item in x if item not in stop_words])

In [29]:
master_df['description_words'][0]

['eager',
 'roll',
 'sleeve',
 'harness',
 'data',
 'drive',
 'policy',
 'change',
 'enjoy',
 'sifting',
 'complex',
 'datasets',
 'illuminate',
 'trend',
 'insight',
 'see',
 'working',
 'value',
 'driven',
 'organization',
 'vision',
 'tackle',
 'pressing',
 'injustice',
 'day',
 'looking',
 'hire',
 'bright',
 'hard',
 'working',
 'creative',
 'individual',
 'strong',
 'data',
 'management',
 'skill',
 'demonstrated',
 'commitment',
 'immigrant',
 'right',
 'data',
 'analyst',
 'assist',
 'analysis',
 'reporting',
 'need',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'working',
 'across',
 'current',
 'project',
 'future',
 'vera',
 'initiative',
 'founded',
 '1961',
 'vera',
 'institute',
 'independent',
 'non',
 'partisan',
 'nonprofit',
 'organization',
 'combine',
 'expertise',
 'research',
 'technical',
 'assistance',
 'demonstration',
 'project',
 'assist',
 'leader',
 'government',
 'civil',
 'society',
 'examine',
 'justice',
 'policy',
 'practice',
 'improve',
 'system',
 'people',
 'rely',
 'justice',
 'safety',
 'study',
 'problem',
 'impede',
 'human',
 'dignity',
 'justice',
 'pilot',
 'solution',
 'transformative',
 'achievable',
 'engage',
 'diverse',
 'community',
 'informed',
 'debate',
 'harness',
 'power',
 'evidence',
 'drive',
 'effective',
 'policy',
 'practice',
 'helping',
 'build',
 'movementamong',
 'government',
 'leader',
 'advocate',
 'immigration',
 'legal',
 'service',
 'communitytowards',
 'universal',
 'legal',
 'representation',
 'immigrant',
 'facing',
 'deportation',
 'face',
 'stepped',
 'immigration',
 'enforcement',
 'million',
 'non',
 'citizen',
 'risk',
 'extended',
 'detention',
 'permanent',
 'separation',
 'family',
 'community',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'partner',
 'government',
 'non',
 'profit',
 'partner',
 'community',
 'improve',
 'government',
 'system',
 'affect',
 'immigrant',
 'family',
 'cij',
 'administers',
 'several',
 'nationwide',
 'legal',
 'service',
 'program',
 'immigrant',
 'facing',
 'deportation',
 'develops',
 'implement',
 'pilot',
 'program',
 'provides',
 'technical',
 'assistance',
 'conduct',
 'independent',
 'research',
 'evaluation',
 'thats',
 'come',
 'data',
 'analyst',
 'support',
 'center',
 'programmatic',
 'effort',
 'regular',
 'monitoring',
 'reporting',
 'federal',
 'government',
 'subcontractor',
 'data',
 'cij',
 'manages',
 'several',
 'proprietary',
 'database',
 'run',
 'aws',
 'caspio',
 'us',
 'sql',
 'r',
 'python',
 'manage',
 'data',
 'opportunity',
 'help',
 'shape',
 'innovative',
 'national',
 'research',
 'policy',
 'agenda',
 'part',
 'dedicated',
 'team',
 'expert',
 'working',
 'improve',
 'access',
 'justice',
 'non',
 'citizen',
 'vera',
 'seek',
 'hire',
 'data',
 'analyst',
 'work',
 'various',
 'data',
 'management',
 'project',
 'center',
 'immigration',
 'justice',
 'cij',
 'collaboration',
 'data',
 'analyst',
 'position',
 'involve',
 'work',
 'across',
 'several',
 'project',
 'unaccompanied',
 'childrens',
 'program',
 'ucp',
 'program',
 'increase',
 'legal',
 'representation',
 'immigrant',
 'child',
 'facing',
 'deportation',
 'without',
 'parent',
 'legal',
 'guardian',
 'position',
 'may',
 'cover',
 'additional',
 'duty',
 'legal',
 'orientation',
 'program',
 'custodian',
 'lopc',
 'educates',
 'custodian',
 'unaccompanied',
 'child',
 'right',
 'immigration',
 'court',
 'process',
 'role',
 'data',
 'analyst',
 'report',
 'member',
 'research',
 'team',
 'work',
 'close',
 'collaboration',
 'vera',
 'staff',
 'ongoing',
 'database',
 'management',
 'monitoring',
 'reporting',
 'analysis',
 'project',
 'youll',
 'support',
 'team',
 'taking',
 'ownership',
 'ongoing',
 'monitoring',
 'reporting',
 'task',
 'involving',
 'large',
 'data',
 'set',
 'principal',
 'responsibility',
 'include',
 'supporting',
 'research',
 'staff',
 'preparing',
 'large',
 'datasets',
 'analysis',
 'including',
 'merging',
 'cleaning',
 'recoding',
 'data',
 'providing',
 'insight',
 'program',
 'performance',
 'summary',
 'statistic',
 'performance',
 'indicator',
 'producing',
 'timely',
 'report',
 'vera',
 'project',
 'team',
 'member',
 'stakeholder',
 'improving',
 'recurring',
 'reporting',
 'process',
 'optimizing',
 'code',
 'producing',
 'subsequent',
 'documentation',
 'coordinating',
 'database',
 'management',
 'task',
 'participating',
 'new',
 'database',
 'design',
 'modifying',
 'existing',
 'database',
 'communicating',
 'outside',
 'engineer',
 'subcontractor',
 'developing',
 'codebooks',
 'delivering',
 'user',
 'training',
 'webinars',
 'database',
 'guide',
 'building',
 'maintaining',
 'interactive',
 'dashboard',
 'documenting',
 'correcting',
 'data',
 'quality',
 'issue',
 'working',
 'supervisor',
 'prioritize',
 'program',
 'need',
 'assisting',
 'project',
 'task',
 'assigned',
 'youre',
 'committed',
 'improving',
 'issue',
 'affecting',
 'immigrant',
 'united',
 'state',
 'applicant',
 'personal',
 'experience',
 'immigration',
 'system',
 'especially',
 'encouraged',
 'apply',
 'youre',
 'getting',
 'started',
 'career',
 '1',
 '2',
 'year',
 'professional',
 'internship',
 'experience',
 'working',
 'large',
 'datasets',
 'preparing',
 'data',
 'analysis',
 'real',
 'enthusiasm',
 'working',
 'data',
 'comfortable',
 'writing',
 'query',
 'sql',
 'r',
 'python',
 'solid',
 'foundation',
 'coding',
 'programming',
 'language',
 'used',
 'manipulate',
 'data',
 'experience',
 'working',
 'collaboratively',
 'using',
 'tool',
 'like',
 'git',
 'github',
 'plus',
 'exceptional',
 'attention',
 'detail',
 'strong',
 'problem',
 'solving',
 'ability',
 'logical',
 'reasoning',
 'skill',
 'ability',
 'detect',
 'anomaly',
 'data',
 'youre',
 'able',
 'work',
 'multiple',
 'project',
 'effectively',
 'efficiently',
 'independently',
 'collaboratively',
 'team',
 'position',
 'involves',
 'working',
 'secure',
 'data',
 'may',
 'require',
 'government',
 'security',
 'clearance',
 'clearance',
 'restricted',
 'u',
 'citizen',
 'citizen',
 'country',
 'party',
 'collective',
 'defense',
 'agreement',
 'u',
 'list',
 'country',
 'detailed',
 'webpage',
 'additional',
 'requirement',
 'clearance',
 'residence',
 'united',
 'state',
 'least',
 'three',
 'last',
 'five',
 'year',
 'apply',
 'please',
 'submit',
 'cover',
 'letter',
 'resume',
 'application',
 'considered',
 'rolling',
 'basis',
 'position',
 'filled',
 'online',
 'submission',
 'pdf',
 'format',
 'preferred',
 'application',
 'cover',
 'letter',
 'attached',
 'considered',
 'cover',
 'letter',
 'address',
 'interest',
 'cij',
 'position',
 'however',
 'necessary',
 'material',
 'may',
 'mailed',
 'faxed',
 'attn',
 'human',
 'resource',
 'cij',
 'data',
 'analyst',
 'recruitment',
 'vera',
 'institute',
 'justice',
 '34',
 '35th',
 'st',
 'suite',
 '4',
 '2a',
 'brooklyn',
 'ny',
 '11232',
 'fax',
 '212',
 '941',
 '9407',
 'please',
 'use',
 'one',
 'method',
 'online',
 'mail',
 'fax',
 'submission',
 'phone',
 'call',
 'please',
 'applicant',
 'selected',
 'interview',
 'contacted',
 'vera',
 'equal',
 'opportunity',
 'affirmative',
 'action',
 'employer',
 'qualified',
 'applicant',
 'considered',
 'employment',
 'without',
 'unlawful',
 'discrimination',
 'based',
 'race',
 'color',
 'creed',
 'national',
 'origin',
 'sex',
 'age',
 'disability',
 'marital',
 'status',
 'sexual',
 'orientation',
 'military',
 'status',
 'prior',
 'record',
 'arrest',
 'conviction',
 'citizenship',
 'status',
 'current',
 'employment',
 'status',
 'caregiver',
 'status',
 'vera',
 'work',
 'advance',
 'justice',
 'particularly',
 'racial',
 'justice',
 'increasingly',
 'multicultural',
 'country',
 'globally',
 'connected',
 'world',
 'value',
 'diverse',
 'experience',
 'including',
 'regard',
 'educational',
 'background',
 'justice',
 'system',
 'contact',
 'depend',
 'diverse',
 'staff',
 'carry',
 'mission',
 'information',
 'vera',
 'cijs',
 'work',
 'please',
 'visit',
 'wwwveraorg',
 'powered',
 'jazzhr']

In [30]:
# master_df['description_words'] = master_df['description_words'].apply(lambda x: ' '.join(str(x)))

In [31]:
nltk.FreqDist(master_df['description_words'][0])

FreqDist({'data': 19, 'justice': 11, 'working': 9, 'vera': 9, 'project': 8, 'immigration': 7, 'cij': 7, 'program': 7, 'immigrant': 6, 'analyst': 6, ...})

In [32]:
master_df['description_words'] = master_df['description_words'] + master_df['description_two_words']
master_df['description_words'][0]

['eager',
 'roll',
 'sleeve',
 'harness',
 'data',
 'drive',
 'policy',
 'change',
 'enjoy',
 'sifting',
 'complex',
 'datasets',
 'illuminate',
 'trend',
 'insight',
 'see',
 'working',
 'value',
 'driven',
 'organization',
 'vision',
 'tackle',
 'pressing',
 'injustice',
 'day',
 'looking',
 'hire',
 'bright',
 'hard',
 'working',
 'creative',
 'individual',
 'strong',
 'data',
 'management',
 'skill',
 'demonstrated',
 'commitment',
 'immigrant',
 'right',
 'data',
 'analyst',
 'assist',
 'analysis',
 'reporting',
 'need',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'working',
 'across',
 'current',
 'project',
 'future',
 'vera',
 'initiative',
 'founded',
 '1961',
 'vera',
 'institute',
 'independent',
 'non',
 'partisan',
 'nonprofit',
 'organization',
 'combine',
 'expertise',
 'research',
 'technical',
 'assistance',
 'demonstration',
 'project',
 'assist',
 'leader',
 'government',
 'civil',
 'society',
 'examine',
 'justice',
 'policy',
 'practice',
 'improve',
 'system',
 'people',
 'rely',
 'justice',
 'safety',
 'study',
 'problem',
 'impede',
 'human',
 'dignity',
 'justice',
 'pilot',
 'solution',
 'transformative',
 'achievable',
 'engage',
 'diverse',
 'community',
 'informed',
 'debate',
 'harness',
 'power',
 'evidence',
 'drive',
 'effective',
 'policy',
 'practice',
 'helping',
 'build',
 'movementamong',
 'government',
 'leader',
 'advocate',
 'immigration',
 'legal',
 'service',
 'communitytowards',
 'universal',
 'legal',
 'representation',
 'immigrant',
 'facing',
 'deportation',
 'face',
 'stepped',
 'immigration',
 'enforcement',
 'million',
 'non',
 'citizen',
 'risk',
 'extended',
 'detention',
 'permanent',
 'separation',
 'family',
 'community',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'partner',
 'government',
 'non',
 'profit',
 'partner',
 'community',
 'improve',
 'government',
 'system',
 'affect',
 'immigrant',
 'family',
 'cij',
 'administers',
 'several',
 'nationwide',
 'legal',
 'service',
 'program',
 'immigrant',
 'facing',
 'deportation',
 'develops',
 'implement',
 'pilot',
 'program',
 'provides',
 'technical',
 'assistance',
 'conduct',
 'independent',
 'research',
 'evaluation',
 'thats',
 'come',
 'data',
 'analyst',
 'support',
 'center',
 'programmatic',
 'effort',
 'regular',
 'monitoring',
 'reporting',
 'federal',
 'government',
 'subcontractor',
 'data',
 'cij',
 'manages',
 'several',
 'proprietary',
 'database',
 'run',
 'aws',
 'caspio',
 'us',
 'sql',
 'r',
 'python',
 'manage',
 'data',
 'opportunity',
 'help',
 'shape',
 'innovative',
 'national',
 'research',
 'policy',
 'agenda',
 'part',
 'dedicated',
 'team',
 'expert',
 'working',
 'improve',
 'access',
 'justice',
 'non',
 'citizen',
 'vera',
 'seek',
 'hire',
 'data',
 'analyst',
 'work',
 'various',
 'data',
 'management',
 'project',
 'center',
 'immigration',
 'justice',
 'cij',
 'collaboration',
 'data',
 'analyst',
 'position',
 'involve',
 'work',
 'across',
 'several',
 'project',
 'unaccompanied',
 'childrens',
 'program',
 'ucp',
 'program',
 'increase',
 'legal',
 'representation',
 'immigrant',
 'child',
 'facing',
 'deportation',
 'without',
 'parent',
 'legal',
 'guardian',
 'position',
 'may',
 'cover',
 'additional',
 'duty',
 'legal',
 'orientation',
 'program',
 'custodian',
 'lopc',
 'educates',
 'custodian',
 'unaccompanied',
 'child',
 'right',
 'immigration',
 'court',
 'process',
 'role',
 'data',
 'analyst',
 'report',
 'member',
 'research',
 'team',
 'work',
 'close',
 'collaboration',
 'vera',
 'staff',
 'ongoing',
 'database',
 'management',
 'monitoring',
 'reporting',
 'analysis',
 'project',
 'youll',
 'support',
 'team',
 'taking',
 'ownership',
 'ongoing',
 'monitoring',
 'reporting',
 'task',
 'involving',
 'large',
 'data',
 'set',
 'principal',
 'responsibility',
 'include',
 'supporting',
 'research',
 'staff',
 'preparing',
 'large',
 'datasets',
 'analysis',
 'including',
 'merging',
 'cleaning',
 'recoding',
 'data',
 'providing',
 'insight',
 'program',
 'performance',
 'summary',
 'statistic',
 'performance',
 'indicator',
 'producing',
 'timely',
 'report',
 'vera',
 'project',
 'team',
 'member',
 'stakeholder',
 'improving',
 'recurring',
 'reporting',
 'process',
 'optimizing',
 'code',
 'producing',
 'subsequent',
 'documentation',
 'coordinating',
 'database',
 'management',
 'task',
 'participating',
 'new',
 'database',
 'design',
 'modifying',
 'existing',
 'database',
 'communicating',
 'outside',
 'engineer',
 'subcontractor',
 'developing',
 'codebooks',
 'delivering',
 'user',
 'training',
 'webinars',
 'database',
 'guide',
 'building',
 'maintaining',
 'interactive',
 'dashboard',
 'documenting',
 'correcting',
 'data',
 'quality',
 'issue',
 'working',
 'supervisor',
 'prioritize',
 'program',
 'need',
 'assisting',
 'project',
 'task',
 'assigned',
 'youre',
 'committed',
 'improving',
 'issue',
 'affecting',
 'immigrant',
 'united',
 'state',
 'applicant',
 'personal',
 'experience',
 'immigration',
 'system',
 'especially',
 'encouraged',
 'apply',
 'youre',
 'getting',
 'started',
 'career',
 '1',
 '2',
 'year',
 'professional',
 'internship',
 'experience',
 'working',
 'large',
 'datasets',
 'preparing',
 'data',
 'analysis',
 'real',
 'enthusiasm',
 'working',
 'data',
 'comfortable',
 'writing',
 'query',
 'sql',
 'r',
 'python',
 'solid',
 'foundation',
 'coding',
 'programming',
 'language',
 'used',
 'manipulate',
 'data',
 'experience',
 'working',
 'collaboratively',
 'using',
 'tool',
 'like',
 'git',
 'github',
 'plus',
 'exceptional',
 'attention',
 'detail',
 'strong',
 'problem',
 'solving',
 'ability',
 'logical',
 'reasoning',
 'skill',
 'ability',
 'detect',
 'anomaly',
 'data',
 'youre',
 'able',
 'work',
 'multiple',
 'project',
 'effectively',
 'efficiently',
 'independently',
 'collaboratively',
 'team',
 'position',
 'involves',
 'working',
 'secure',
 'data',
 'may',
 'require',
 'government',
 'security',
 'clearance',
 'clearance',
 'restricted',
 'u',
 'citizen',
 'citizen',
 'country',
 'party',
 'collective',
 'defense',
 'agreement',
 'u',
 'list',
 'country',
 'detailed',
 'webpage',
 'additional',
 'requirement',
 'clearance',
 'residence',
 'united',
 'state',
 'least',
 'three',
 'last',
 'five',
 'year',
 'apply',
 'please',
 'submit',
 'cover',
 'letter',
 'resume',
 'application',
 'considered',
 'rolling',
 'basis',
 'position',
 'filled',
 'online',
 'submission',
 'pdf',
 'format',
 'preferred',
 'application',
 'cover',
 'letter',
 'attached',
 'considered',
 'cover',
 'letter',
 'address',
 'interest',
 'cij',
 'position',
 'however',
 'necessary',
 'material',
 'may',
 'mailed',
 'faxed',
 'attn',
 'human',
 'resource',
 'cij',
 'data',
 'analyst',
 'recruitment',
 'vera',
 'institute',
 'justice',
 '34',
 '35th',
 'st',
 'suite',
 '4',
 '2a',
 'brooklyn',
 'ny',
 '11232',
 'fax',
 '212',
 '941',
 '9407',
 'please',
 'use',
 'one',
 'method',
 'online',
 'mail',
 'fax',
 'submission',
 'phone',
 'call',
 'please',
 'applicant',
 'selected',
 'interview',
 'contacted',
 'vera',
 'equal',
 'opportunity',
 'affirmative',
 'action',
 'employer',
 'qualified',
 'applicant',
 'considered',
 'employment',
 'without',
 'unlawful',
 'discrimination',
 'based',
 'race',
 'color',
 'creed',
 'national',
 'origin',
 'sex',
 'age',
 'disability',
 'marital',
 'status',
 'sexual',
 'orientation',
 'military',
 'status',
 'prior',
 'record',
 'arrest',
 'conviction',
 'citizenship',
 'status',
 'current',
 'employment',
 'status',
 'caregiver',
 'status',
 'vera',
 'work',
 'advance',
 'justice',
 'particularly',
 'racial',
 'justice',
 'increasingly',
 'multicultural',
 'country',
 'globally',
 'connected',
 'world',
 'value',
 'diverse',
 'experience',
 'including',
 'regard',
 'educational',
 'background',
 'justice',
 'system',
 'contact',
 'depend',
 'diverse',
 'staff',
 'carry',
 'mission',
 'information',
 'vera',
 'cijs',
 'work',
 'please',
 'visit',
 'wwwveraorg',
 'powered',
 'jazzhr',
 'eager roll',
 'roll sleeve',
 'sleeve harness',
 'harness data',
 'data drive',
 'drive policy',
 'policy change',
 'change enjoy',
 'enjoy sifting',
 'sifting complex',
 'complex datasets',
 'datasets illuminate',
 'illuminate trend',
 'trend insight',
 'insight see',
 'see working',
 'working value',
 'value driven',
 'driven organization',
 'organization vision',
 'vision tackle',
 'tackle pressing',
 'pressing injustice',
 'injustice day',
 'day looking',
 'looking hire',
 'hire bright',
 'bright hard',
 'hard working',
 'working creative',
 'creative individual',
 'individual strong',
 'strong data',
 'data management',
 'management skill',
 'skill demonstrated',
 'demonstrated commitment',
 'commitment immigrant',
 'immigrant right',
 'right data',
 'data analyst',
 'analyst assist',
 'assist analysis',
 'analysis reporting',
 'reporting need',
 'need veras',
 'veras center',
 'center immigration',
 'immigration justice',
 'justice cij',
 'cij working',
 'working across',
 'across current',
 'current project',
 'project future',
 'future vera',
 'vera initiative',
 'initiative founded',
 'founded 1961',
 '1961 vera',
 'vera institute',
 'institute independent',
 'independent non',
 'non partisan',
 'partisan nonprofit',
 'nonprofit organization',
 'organization combine',
 'combine expertise',
 'expertise research',
 'research technical',
 'technical assistance',
 'assistance demonstration',
 'demonstration project',
 'project assist',
 'assist leader',
 'leader government',
 'government civil',
 'civil society',
 'society examine',
 'examine justice',
 'justice policy',
 'policy practice',
 'practice improve',
 'improve system',
 'system people',
 'people rely',
 'rely justice',
 'justice safety',
 'safety study',
 'study problem',
 'problem impede',
 'impede human',
 'human dignity',
 'dignity justice',
 'justice pilot',
 'pilot solution',
 'solution transformative',
 'transformative achievable',
 'achievable engage',
 'engage diverse',
 'diverse community',
 'community informed',
 'informed debate',
 'debate harness',
 'harness power',
 'power evidence',
 'evidence drive',
 'drive effective',
 'effective policy',
 'policy practice',
 'practice helping',
 'helping build',
 'build movementamong',
 'movementamong government',
 'government leader',
 'leader advocate',
 'advocate immigration',
 'immigration legal',
 'legal service',
 'service communitytowards',
 'communitytowards universal',
 'universal legal',
 'legal representation',
 'representation immigrant',
 'immigrant facing',
 'facing deportation',
 'deportation face',
 'face stepped',
 'stepped immigration',
 'immigration enforcement',
 'enforcement million',
 'million non',
 'non citizen',
 'citizen risk',
 'risk extended',
 'extended detention',
 'detention permanent',
 'permanent separation',
 'separation family',
 'family community',
 'community veras',
 'veras center',
 'center immigration',
 'immigration justice',
 'justice cij',
 'cij partner',
 'partner government',
 'government non',
 'non profit',
 'profit partner',
 'partner community',
 'community improve',
 'improve government',
 'government system',
 'system affect',
 'affect immigrant',
 'immigrant family',
 'family cij',
 'cij administers',
 'administers several',
 'several nationwide',
 'nationwide legal',
 'legal service',
 'service program',
 'program immigrant',
 'immigrant facing',
 'facing deportation',
 'deportation develops',
 'develops implement',
 'implement pilot',
 'pilot program',
 'program provides',
 'provides technical',
 'technical assistance',
 'assistance conduct',
 'conduct independent',
 'independent research',
 'research evaluation',
 'evaluation thats',
 'thats come',
 'come data',
 'data analyst',
 'analyst support',
 'support center',
 'center programmatic',
 'programmatic effort',
 'effort regular',
 'regular monitoring',
 'monitoring reporting',
 'reporting federal',
 'federal government',
 'government subcontractor',
 'subcontractor data',
 'data cij',
 'cij manages',
 'manages several',
 'several proprietary',
 'proprietary database',
 'database run',
 'run aws',
 'aws caspio',
 'caspio us',
 'us sql',
 'sql r',
 'r python',
 'python manage',
 'manage data',
 'data opportunity',
 'opportunity help',
 'help shape',
 'shape innovative',
 'innovative national',
 'national research',
 'research policy',
 'policy agenda',
 'agenda part',
 'part dedicated',
 'dedicated team',
 'team expert',
 'expert working',
 'working improve',
 'improve access',
 'access justice',
 'justice non',
 'non citizen',
 'citizen vera',
 'vera seek',
 'seek hire',
 'hire data',
 'data analyst',
 'analyst work',
 'work various',
 'various data',
 'data management',
 'management project',
 'project center',
 'center immigration',
 'immigration justice',
 'justice cij',
 'cij collaboration',
 'collaboration data',
 'data analyst',
 'analyst position',
 'position involve',
 'involve work',
 'work across',
 'across several',
 'several project',
 'project unaccompanied',
 'unaccompanied childrens',
 'childrens program',
 'program ucp',
 'ucp program',
 'program increase',
 'increase legal',
 'legal representation',
 'representation immigrant',
 'immigrant child',
 'child facing',
 'facing deportation',
 'deportation without',
 'without parent',
 'parent legal',
 'legal guardian',
 'guardian position',
 'position may',
 'may cover',
 'cover additional',
 'additional duty',
 'duty legal',
 'legal orientation',
 'orientation program',
 'program custodian',
 'custodian lopc',
 'lopc educates',
 'educates custodian',
 'custodian unaccompanied',
 'unaccompanied child',
 'child right',
 'right immigration',
 'immigration court',
 'court process',
 'process role',
 'role data',
 'data analyst',
 'analyst report',
 'report member',
 'member research',
 'research team',
 'team work',
 'work close',
 'close collaboration',
 'collaboration vera',
 'vera staff',
 'staff ongoing',
 'ongoing database',
 'database management',
 'management monitoring',
 'monitoring reporting',
 'reporting analysis',
 'analysis project',
 'project youll',
 'youll support',
 'support team',
 'team taking',
 'taking ownership',
 'ownership ongoing',
 'ongoing monitoring',
 'monitoring reporting',
 'reporting task',
 'task involving',
 'involving large',
 'large data',
 'data set',
 'set principal',
 'principal responsibility',
 'responsibility include',
 'include supporting',
 'supporting research',
 'research staff',
 'staff preparing',
 'preparing large',
 'large datasets',
 'datasets analysis',
 'analysis including',
 'including merging',
 'merging cleaning',
 'cleaning recoding',
 'recoding data',
 'data providing',
 'providing insight',
 'insight program',
 'program performance',
 'performance summary',
 'summary statistic',
 'statistic performance',
 'performance indicator',
 ...]

In [33]:
my_languages = ["abap", "actionscript", "ada", "algol", "alice", "apl", "asp", "aspnet", "assembly" "language",
                "assembly language", "awk", "bbc", "bbcbasic", "bbc basic", "c", "c++", "c#", "cobol", "delphi", # "d"
                "dreamweaver", "erlang", "elixir", "erlang and elixir", "f#", "forth", "fortran", # "functional", "programming"
                "functional programming", "haskell", "html", "idl", "idl", "intercal", "java", "javascript", "node", "js", # "go"
                "node.js", "jquery", "bootstrap" "labview","lisp","metaquotes language","metaquoteslanguage","ml","modula-3",
                "msaccess","ms access","mysql","nxt-g","object-oriented programming","objective-c","ocaml","pascal","perl",
                "php","pl/sql","postgresql","postscript","prolog","puredata","python","r","rapidweaver","ravendb","rexx",
                "ruby on rails","Rubyonrails","s-plus","sas","scala","sed","sgml","simula","smalltalk","smil","snobol",
                "sql","sqlite","ssi","stata","swift","tcl/tk","tex and latex","texandlatex","unified modeling language",
                "unix shells","unixshells","verilog","vhdl","visualbasi","visual basis","vrml","wap/wml","xml","xsl",
                "julia", "shell"]

In [34]:
my_tools = ["microsoft excel", "excel", "tableau", # "microsoft"
            "rapidminer", "knime", "power bi", "bi", "apache spark",
            "apache", "spark", "qlikview", "qlik", "talend", "splunk", "businessobjects",
            "sap", "sap businessobjects", "sisense", "tibco spotfire", "tibco",
            "spotfire", "thoughtspot", "sas business intelligence", "sas", "business intelligence",
            "google data studio", "data studio", "google analytics", "redash", "periscope data",
            "periscope", "metabase", "jupyter notebook", "jupyter", "notebook", "ibm cognos", "ibm",
            "cognos", "chartio", "mode", "looker", "domo", "oracle analytics cloud", "oracle",
            "oracle analytics", "analytics cloud", "oracle cloud", "github"] # "git"

In [35]:
my_databases = ["mysql", "postgresql", "microsoft sql server", "sql server", "mongodb", "mongo",
                "oracle", "remote dictionary server", "redis", "elasticsearch", "mariadb",
                "ibm db2", "sqlite", "amazon dynamodb", "dynamodb", "aws", "azure cosmos db",
                "azure", "cosmos", "cosmos db", "azure cosmos", "azure db", "azuredb",
                "amazon keyspaces", "keyspaces", "amazon documentdb", "documentdb", "amazon redshift",
                "redshift", "cassandra", "hbase", "neo4j", "couchdb", "orientdb", "terrstore",
                "flockdb", "hibari", "riak", "pig", "hive", "impala"]

In [36]:
my_softskills = ["communication", "curiosity", "business acumen", "storytelling",
                "adaptability", "critical thinking", "product understanding", "team plater",
                "problem solving", "problem-solving", "research oriented", "attention to detail", # "research"
                "teamwork", "critical-thinking", "data visualizations", "data visualisations",
                "data modeling", "data mining", "data cleaning", "mathematics", "customer service",
                "customer", "customer management", "management", "scheduling", "time management",
                "project management", "analytical thinking", "flexibility", "leadership",
                "creativity", "work ethic", "stress management", "organization", "prioritizing",
                "planning", "goal setting", "goal oriented", "verbal communication", "written communication",
                "presentation", "constructive feedback", "active listening", "self-management",
                "self management", "optimism", "positive outlook", "calmness", "patience", "self-motivation",
                "self motivation", "self motivating", "self-motivating", "logical", "logical reasoning", "decision making",
                "decision-making", "conflict management", "conflict resolution", "coordination", "collaboration",
                "idea exchange", "mediation", "imagination", "mind mapping", "innovation", "experimentation",
                "questioning", "out side the box", "out-side-the-box", "management skills", "authenticity",
                "mentorship", "generosity", "cultural intelligence", "empathy", "humor", "networking",
                "tolerance", "diplomacy", "responsibility", "discipline", "dependability", "reliability",
                "commitment", "professionalism", "introspection", "acuity", "critical observation",
                "positive attitude", "self control" "assertiveness", "empathy", "taking responsibility",
                "positivity", "team work", "confidence", "welcoming", "willingness to learn", "multitasking",
                "multi tasking", "tenacity", "honesty", "accepting criticism", "motivation", "negotiation",
                "charisma", "public speaking", "oral communication", "persuasion", "visual communication",
                "aesthetics", "system analysis", "deductive reasoning", "active learning", "accuracy",
                "client relations", "client service", "strategic thinking", "technical writing",
                "team building", "public thinking", "open mindedness", "data-mining", "mining"]

In [37]:
master_df['description_languages'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_languages])
master_df['description_tools'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_tools])
master_df['description_databases'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_databases])
master_df['description_softskills'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_softskills])

In [38]:
master_df['description_languages'][0]

['sql', 'r', 'python', 'sql', 'r', 'python']

In [39]:
master_df

,job_title,job_description,clean_description,description_two_words,description_words,description_languages,description_tools,description_databases,description_softskills
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...,"[eager roll, roll sleeve, sleeve harness, harn...","[eager, roll, sleeve, harness, data, drive, po...","[sql, r, python, sql, r, python]",[github],[aws],"[organization, management, commitment, organiz..."
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...,"[overview provides, provides analytical, analy...","[overview, provides, analytical, technical, su...","[sql, sql, r, stata]","[excel, excel, excel, excel, business intellig...",[],"[management, management, responsibility, manag..."
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...,"[looking senior, senior data, data analyst, an...","[’, looking, senior, data, analyst, ha, love, ...","[sql, r, python, sql, r, python]","[excel, bi, bi, chartio, looker, tableau]",[],"[mentorship, customer, customer, organization,..."
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...,"[requisition numberrr, numberrr 0001939, 00019...","[requisition, numberrr, 0001939, remoteyes, co...","[sql, sql, sql]",[tableau],[],"[curiosity, teamwork, flexibility, generosity,..."
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...,"[fanduel group, group fanduel, fanduel group, ...","[fanduel, group, fanduel, group, world, class,...","[sql, sql, python]",[excel],[],"[accuracy, mentorship]"
...,...,...,...,...,...,...,...,...,...
8127,Senior Performance Marketing (Data Analyst),"At Edward Jones, we help clients achieve their...",edward jones help client achieve serious long ...,"[edward jones, jones help, help client, client...","[edward, jones, help, client, achieve, serious...","[sql, sql, xml, r, python]","[oracle, excel, tableau, google analytics, mic...","[oracle, impala, hive, pig]","[mentorship, communication, organization, lead..."
8128,"Data Analyst, Developer Operations","Summary:\n\nMeta Platforms, Inc. (Meta), forme...",summary meta platform inc meta formerly known ...,"[summary meta, meta platform, platform inc, in...","[summary, meta, platform, inc, meta, formerly,...","[sql, python]","[tableau, qlikview]",[],"[responsibility, mining, experimentation, lead..."
8129,Data Science/Data Analyst Internship - Summer ...,Description\n\nWho are we...\n\nAt Koch Indust...,description koch industry mission help people ...,"[description koch, koch industry, industry mis...","[description, koch, industry, mission, help, p...",[],[],[],"[mining, curiosity, communication, flexibility..."
8130,2023 Internship- Associate Data Analyst,2023 Internship Associate Data Analyst\n\nDes...,2023 internship associate data analyst descrip...,"[2023 internship, internship associate, associ...","[2023, internship, associate, data, analyst, d...","[sql, r, python, sql, c]","[bi, bi, bi, tableau, power bi, power bi, powe...",[],"[responsibility, organization, leadership, org..."
8131,Jr. Data Analyst,Staffigo is in the business of providing IT Co...,staffigo business providing consulting service...,"[staffigo business, business providing, provid...","[staffigo, business, providing, consulting, se...",[],"[excel, oracle, bi, tableau, power bi]",[oracle],"[responsibility, management, management, manag..."

In [40]:
master_df.head(20)

,job_title,job_description,clean_description,description_two_words,description_words,description_languages,description_tools,description_databases,description_softskills
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,eager roll sleeve harness data drive policy ch...,"[eager roll, roll sleeve, sleeve harness, harn...","[eager, roll, sleeve, harness, data, drive, po...","[sql, r, python, sql, r, python]",[github],[aws],"[organization, management, commitment, organiz..."
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,overview provides analytical technical support...,"[overview provides, provides analytical, analy...","[overview, provides, analytical, technical, su...","[sql, sql, r, stata]","[excel, excel, excel, excel, business intellig...",[],"[management, management, responsibility, manag..."
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,’ looking senior data analyst ha love mentorsh...,"[looking senior, senior data, data analyst, an...","[’, looking, senior, data, analyst, ha, love, ...","[sql, r, python, sql, r, python]","[excel, bi, bi, chartio, looker, tableau]",[],"[mentorship, customer, customer, organization,..."
3,Data Analyst,Requisition NumberRR 0001939\nRemote:Yes\nWe c...,requisition numberrr 0001939 remoteyes collabo...,"[requisition numberrr, numberrr 0001939, 00019...","[requisition, numberrr, 0001939, remoteyes, co...","[sql, sql, sql]",[tableau],[],"[curiosity, teamwork, flexibility, generosity,..."
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,fanduel group fanduel group world class team b...,"[fanduel group, group fanduel, fanduel group, ...","[fanduel, group, fanduel, group, world, class,...","[sql, sql, python]",[excel],[],"[accuracy, mentorship]"
5,Data Analyst,About Cubist\nCubist Systematic Strategies is ...,cubist cubist systematic strategy one world ’ ...,"[cubist cubist, cubist systematic, systematic ...","[cubist, cubist, systematic, strategy, one, wo...","[sql, python, c, c++, java]",[excel],[],"[responsibility, scheduling, presentation, org..."
6,Business/Data Analyst (FP&A),Two Sigma is a different kind of investment ma...,two sigma different kind investment manager si...,"[two sigma, sigma different, different kind, k...","[two, sigma, different, kind, investment, mana...","[python, sql]",[excel],[],"[planning, management, responsibility, managem..."
7,Data Science Analyst,Data Science Analyst\n\nJob Details\nLevel\nEx...,data science analyst job detail level experien...,"[data science, science analyst, analyst job, j...","[data, science, analyst, job, detail, level, e...","[r, python, sql]",[],[],"[customer, responsibility, mathematics, mining..."
8,Data Analyst,The Data Analyst is an integral member of the ...,data analyst integral member global commercial...,"[data analyst, analyst integral, integral memb...","[data, analyst, integral, member, global, comm...","[sql, python, r, scala]","[excel, spark]",[],"[responsibility, customer, management, data mo..."
9,"Data Analyst, Merchant Health",About Us\n\nRiskified is the AI platform power...,u riskified ai platform powering ecommerce rev...,"[u riskified, riskified ai, ai platform, platf...","[u, riskified, ai, platform, powering, ecommer...","[r, sql, sql, r, python]",[],[],"[customer, customer, customer, customer, custo..."
10,Data Analyst,NYU Grossman School of Medicine is one of the ...,nyu grossman school medicine one nation ’ top ...,"[nyu grossman, grossman school, school medicin...","[nyu, grossman, school, medicine, one, nation,...","[stata, r]",[],[],"[innovation, management, planning, responsibil..."
11,Data Analyst,BulbHead is currently seeking a Data Analyst t...,bulbhead currently seeking data analyst join t...,"[bulbhead currently, currently seeking, seekin...","[bulbhead, currently, seeking, data, analyst, ...","[sql, python, sql, python, r, sql, python]","[excel, tableau, chartio, looker]",[],"[curiosity, customer, responsibility, commitme..."
12,DATA ANALYST,Job Summary:\n\nThe Clinical Research Data Ana...,job summary clinical research data analyst ped...,"[job summary, summary clinical, clinical resea...","[job, summary, clinical, research, data, analy...",[],[],[],"[coordination, management, responsibility, acc..."
13,Senior Data Analyst,About Known\n\nKnown is a modern marketing com...,known known modern marketing company engineere...,"[known known, known modern, modern marketing, ...","[known, known, modern, marketing, company, eng...","[python, sql]",[excel],[],"[flexibility, communication, presentation, acc..."
14,Investment Advisory Data Analyst,Investment Advisory Compliance Opportunity in ...,investment advisory compliance opportunity fin...,"[investment advisory, advisory compliance, com...","[investment, advisory, compliance, opportunity...",[sql],[excel],[sql server],"[responsibility, communication, verbal communi..."
15,Sustainability Data Analyst,Job Description\nRole Description\n\nSustainab...,job description role description sustainabilit...,"[job description, description role, role descr...","[job, description, role, description, sustaina...","[sql, r, python]",[excel],[],"[responsibility, responsibility, management, m..."
16,Data Analyst,Undertone stands alone among AdTech and ad net...,undertone stand alone among adtech ad network ...,"[undertone stand, stand alone, alone among, am...","[undertone, stand, alone, among, adtech, ad, n...","[sql, sql]","[tableau, tableau, business intelligence, busi...",[],"[management, organization, customer, responsib..."
17,Clinical Data Analyst,About Us:\n\nNYSTEC is a non profit technology...,u nystec non profit technology consulting comp...,"[u nystec, nystec non, non profit, profit tech...","[u, nystec, non, profit, technology, consultin...","[sql, python]",[],[],"[organization, organization, responsibility, c..."
18,DATA PROGRAMMER/ANALYST,Company Description\n\nEDUCATION DEVELOPMENT C...,company description education development cent...,"[company description, description education, e...","[company, description, education, development,...","[python, java]",[],[],"[collaboration, mathematics, mathematics, mana..."
19,Data Analyst,"About Us\n\nAt Teachers Pay Teachers (TpT), we...",u teacher pay teacher tpt unlocking power educ...,"[u teacher, teacher pay, pay teacher, teacher ...","[u, teacher, pay, teacher, tpt, unlocking, pow...","[sql, python, r, ml]","[bi, looker, business intelligence]",[],"[commitment, planning, teamwork, organization,..."

In [41]:
master_df["job_description"][1029]

'Na Ali’i is seeking a financial data analyst to support the Office of Financial Operations (FMO) within the Assistant Secretary of the Navy (Financial Management & Comptroller) (ASN(FM&C)), in areas such as Financial Improvement and Audit Readiness Program Support, Program Management Support, Financial Management and Accounting Operations, and Systems Support. This position will support FMO in providing timely, accurate, and useful information for policies, procedures, and direction on accounting, finance, management control, financial services, and financial systems, as well as serve as liaison with external organizations for financial operations.\n\nLeverage analytical and data mining skills to process a variety of information, evaluate costs and benefits, and solve complex financial problems.\nConduct research and analyze data and review financial budget data. Conduct variance analysis and perform data reconciliations. Provide data analysis and data visualization support to derive actionable insights using tools MS Excel, Access, and other MS Office suite applications.\nPrepare routine correspondence, reports and briefings, and prepare and deliver actionable information in presentations appropriate for senior level managers and non technical audiences.\nReview operating budgets, analyze trends and identifying ways to improve efficiency and increase profits.\nProvide financial management support to client in various aspects of the Planning, Programming, Budgeting, Execution (PPBE) and reporting of FMO budget requirements as it relates to FMO operational requirements and audit readiness and to all appropriate stakeholders.\nAnalyze the budget and its execution strategy to include planning, scheduling, and coordinating actions in all phases of budgeting and execution activities for multi year Financial Improvement and Audit Readiness (FIAR) programs\nAnalyze and report data from PBIS, STARS, SABRS and other budget and execution tools.\n\nSkills Qualifications: Candidate should possess:\nExercises substantial autonomy in the day to day planning and management of work requirements. Demonstrates accuracy and thoroughness; looks for ways to improve and promote quality; applies feedback to improve performance; monitors own work to ensure quality. Works collaboratively and exercises solid judgement in decision making.\nExcellent technical skills, organizational and planning skills, communication, and problem solving skills, problem analysis, takes initiative and is adaptable and customer service oriented. Specifically, the ideal candidate will be familiar with, and have experience in working with large datasets or databases and possess strong quantitative ability and a keen eye for detail and accuracy.\nProficiency in Microsoft Office applications with emphasis in Word, Excel, Outlook, and on line search engines required.\nUnderstanding of the DON budget processes, systems, structures, policy and guidance desirable. Familiarity with SABRS and PBIS desirable.\nSupportive of and collaborates effectively with co workers to provide high quality outcomes in support of client requirements.\nHigh standards for professional conduct in dealing with co workers and clients.\nEducation and Experience:\nThis position requires a bachelor’s degree or higher in data science analytics, statistics, mathematics, business management or an equivalent related field from an accredited institution. A minimum of three (3) years of progressive relevant professional experience in financial, cost, or operations research analysis support is required.\nExperience working in or directly for Navy headquarters organizations is desirable.\nMilitary Installation Access: This position resides on a military installation or within a government facility. Candidate must be able to qualify for and maintain a Common Access Card.\nClearance: This position requires an active SECRET security clearance.\nThe Nakupuna Companies are employers of equal opportunity that are committed to hiring a diverse workforce. All qualified applicants receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity and expression, age, ancestry, marital status, genetic information, national origin, disability or veteran status.'

In [42]:
google_job_df2

,job_title,job_description
0,Data Analyst,Job Posting Title\nData Analyst\n...\nAgency\n...
1,Data Analyst (Marketing),About The Role\n\nAbout Us...\n\nWe’re Entain....
2,People Analytics Data Analyst (Talent Acquisit...,Job Description\nPeople Analytics CoE (Communi...
3,Data Analyst,Pernod Ricard is now hiring Data Analyst in Un...
4,Sr Systems Data Analyst,Type of Requisition: Regular\n\nClearance Leve...
...,...,...
1965,Senior Performance Marketing (Data Analyst),"At Edward Jones, we help clients achieve their..."
1966,"Data Analyst, Developer Operations","Summary:\n\nMeta Platforms, Inc. (Meta), forme..."
1967,Data Science/Data Analyst Internship - Summer ...,Description\n\nWho are we...\n\nAt Koch Indust...
1968,2023 Internship- Associate Data Analyst,2023 Internship- Associate Data Analyst\n\nDes...
1969,Jr. Data Analyst,Staffigo is in the business of providing IT Co...

In [43]:
master_df['description_softskills'][1029]

['management',
 'management',
 'management',
 'management',
 'organization',
 'mining',
 'presentation',
 'management',
 'planning',
 'planning',
 'scheduling',
 'planning',
 'management',
 'accuracy',
 'planning',
 'communication',
 'customer',
 'accuracy',
 'mathematics',
 'management',
 'organization',
 'data mining',
 'decision making',
 'problem solving',
 'customer service']

In [44]:
master_df[1033:1035]

,job_title,job_description,clean_description,description_two_words,description_words,description_languages,description_tools,description_databases,description_softskills
1033,Senior Data Analyst,"Here at Discount Tire, we celebrate the spirit...",discount tire celebrate spirit people extraord...,"[discount tire, tire celebrate, celebrate spir...","[discount, tire, celebrate, spirit, people, ex...","[sql, python, perl, javascript, shell, sql, r,...","[bi, tableau, excel]","[pig, hive, impala]","[customer, customer, customer, customer, custo..."
1034,Data Engineer/Database Analyst/Data Analyst,Company Description\n\nFortune 500 Company\n\n...,company description fortune 500 company job de...,"[company description, description fortune, for...","[company, description, fortune, 500, company, ...",[],[],[],"[responsibility, management, management, minin..."

In [45]:
master_df.query("job_title == 'Financial Data Analyst'")

,job_title,job_description,clean_description,description_two_words,description_words,description_languages,description_tools,description_databases,description_softskills
255,Financial Data Analyst,Job Description: https: jobs.lever.co ltse 8d...,job description http jobsleverco ltse 8d671b9b...,"[job description, description http, http jobsl...","[job, description, http, jobsleverco, ltse, 8d...",[sql],"[excel, excel]",[],"[customer, customer, customer, commitment, tol..."
447,Financial Data Analyst,"If you are a current Vivint Solar employee, pl...",current vivint solar employee please apply pos...,"[current vivint, vivint solar, solar employee,...","[current, vivint, solar, employee, please, app...","[sql, python, sql, python]","[excel, bi, microsoft excel]",[],"[management, management, responsibility, accur..."
604,Financial Data Analyst,"Financial Data Analyst\nLocation: El Segundo, ...",financial data analyst location el segundo ca ...,"[financial data, data analyst, analyst locatio...","[financial, data, analyst, location, el, segun...",[],[],[],"[discipline, organization, communication, pres..."
889,Financial Data Analyst,Financial Analyst\n\nCompany Overview\n\nLumin...,financial analyst company overview luminess ho...,"[financial analyst, analyst company, company o...","[financial, analyst, company, overview, lumine...",[sql],"[excel, tableau, excel, tableau, microsoft excel]",[],"[customer, responsibility, discipline, managem..."
1029,Financial Data Analyst,Na Ali’i is seeking a financial data analyst t...,na ali ’ seeking financial data analyst suppor...,"[na alii, alii seeking, seeking financial, fin...","[na, ali, ’, seeking, financial, data, analyst...",[],"[excel, excel]",[],"[management, management, management, managemen..."
1423,Financial Data Analyst,CarOffer is rapidly growing their Accounting F...,caroffer rapidly growing accounting finance te...,"[caroffer rapidly, rapidly growing, growing ac...","[caroffer, rapidly, growing, accounting, finan...",[],[excel],[],"[responsibility, responsibility, leadership, b..."
1517,Financial Data Analyst,"Posted: Feb 24, 2020\nWeekly Hours: 40\nRole N...",posted feb 24 2020 weekly hour 40 role number ...,"[posted feb, feb 24, 24 2020, 2020 weekly, wee...","[posted, feb, 24, 2020, weekly, hour, 40, role...","[sql, r, python]","[tableau, sap, excel, bi, tableau]",[],"[customer, communication, organization, innova..."
1532,Financial Data Analyst,About the company\n\nRobinhood is democratizin...,company robinhood democratizing finance custom...,"[company robinhood, robinhood democratizing, d...","[company, robinhood, democratizing, finance, c...",[sql],"[looker, oracle]",[oracle],"[customer, accuracy]"
1778,Financial Data Analyst,Aspen Careers is currently working with a down...,aspen career currently working downtown firm l...,"[aspen career, career currently, currently wor...","[aspen, career, currently, working, downtown, ...",[],[excel],[],"[accuracy, planning, decision making]"
1806,Financial Data Analyst,Financial Data Analyst**job details:**+ locati...,financial data analystjob details+ locationcha...,"[financial data, data analystjob, analystjob d...","[financial, data, analystjob, details+, locati...","[sql, sql]","[bi, bi, bi, power bi, power bi, power bi]",[azure],"[organization, innovation, responsibility, man..."
2202,Financial Data Analyst,Position:Financial Data AnalystJob Description...,positionfinancial data analystjob descriptionb...,"[positionfinancial data, data analystjob, anal...","[positionfinancial, data, analystjob, descript...","[sql, c++]",[excel],[],"[responsibility, accuracy, communication, cust..."
2219,Financial Data Analyst,Black Knight is the premier provider of integr...,black knight premier provider integrated techn...,"[black knight, knight premier, premier provide...","[black, knight, premier, provider, integrated,...","[sql, c++]",[excel],[],"[responsibility, accuracy, communication, cust..."
3403,Financial Data Analyst,Financial Analyst\n\nCompany Overview\n\nLumin...,financial analyst company overview luminess ho...,"[financial analyst, analyst company, company o...","[financial, analyst, company, overview, lumine...",[sql],"[excel, tableau, excel, tableau, microsoft excel]",[],"[customer, responsibility, discipline, managem..."
3774,Financial Data Analyst,Na Ali’i is seeking a financial data analyst t...,na ali ’ seeking financial data analyst suppor...,"[na alii, alii seeking, seeking financial, fin...","[na, ali, ’, seeking, financial, data, analyst...",[],"[excel, excel]",[],"[management, management, management, managemen..."
6119,Financial Data Analyst,Aspen Careers is currently working with a down...,aspen career currently working downtown firm l...,"[aspen career, career currently, currently wor...","[aspen, career, currently, working, downtown, ...",[],[excel],[],"[accuracy, planning, decision making]"
6921,Financial Data Analyst,The Financial Data Analyst will visualize data...,financial data analyst visualize data ensure i...,"[financial data, data analyst, analyst visuali...","[financial, data, analyst, visualize, data, en...",[sql],"[tableau, tableau]",[],"[organization, organization, leadership, respo..."
7376,Financial Data Analyst,Overview\n\nPublic Consulting Group (PCG) is a...,overview public consulting group pcg leading p...,"[overview public, public consulting, consultin...","[overview, public, consulting, group, pcg, lea...",[],"[excel, excel]",[],"[management, responsibility, presentation, man..."
7654,Financial Data Analyst,Overview\n\nPublic Consulting Group (PCG) is a...,overview public consulting group pcg leading p...,"[overview public, public consulting, consultin...","[overview, public, consulting, group, pcg, lea...",[],"[excel, excel]",[],"[management, responsibility, presentation, man..."
7751,Financial Data Analyst,Key Accountabilities\n\n Data analysis and re...,key accountability data analysis reconciliatio...,"[key accountability, accountability data, data...","[key, accountability, data, analysis, reconcil...","[sql, sql]","[excel, microsoft excel]",[],"[management, logical, coordination, responsibi..."
7752,Financial Data Analyst,Key Accountabilities\n\n Data analysis and re...,key accountability data analysis reconciliatio...,"[key accountability, accountability data, data...","[key, accountability, data, analysis, reconcil...","[sql, sql]","[excel, microsoft excel]",[],"[management, logical, coordination, responsibi..."
7821,Financial Data Analyst,Job description\n\nMust Have...\n\nFinancial A...,job description must financial analysis job su...,"[job description, description must, must finan...","[job, description, must, financial, analysis, ...",[],"[excel, excel, excel, microsoft excel]",[],"[customer, management, responsibility, managem..."
7927,Financial Data Analyst,The Financial Data Analyst will visualize data...,financial data analyst visualize data ensure i...,"[financial data, data analyst, analyst visuali...","[financial, data, analyst, visualize, data, en...",[sql],"[tableau, tableau]",[],"[organization, organization, leadership, respo..."