In [360]:
# Make a data directory and copy .env and functions.py

datadir = 'data/'
# !mkdir {datadir}
# !cp ../repositories/da-external-data-sourcing/sql_functions.py . 
# !cp ../repositories/da-external-data-sourcing/.env .

In [361]:
import pandas as pd

In [362]:
analyst_df = pd.read_csv('dataset/DataAnalyst.csv')
scientist_df = pd.read_csv('dataset/DataScientist.csv')
jobs_df = pd.read_csv('dataset/gsearch_jobs 3.csv')

In [363]:
display(analyst_df.info())
display(scientist_df.info())
display(jobs_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2253 non-null   int64
 1   Job Title          2253 non-null   object
 2   Salary Estimate    2253 non-null   object
 3   Job Description    2253 non-null   object
 4   Rating             2253 non-null   float64
 5   Company Name       2252 non-null   object
 6   Location           2253 non-null   object
 7   Headquarters       2253 non-null   object
 8   Size               2253 non-null   object
 9   Founded            2253 non-null   int64
 10  Type of ownership  2253 non-null   object
 11  Industry           2253 non-null   object
 12  Sector             2253 non-null   object
 13  Revenue            2253 non-null   object
 14  Competitors        2253 non-null   object
 15  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 281.8+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3909 entries, 0 to 3908
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3909 non-null   int64
 1   index              3909 non-null   int64
 2   Job Title          3909 non-null   object
 3   Salary Estimate    3909 non-null   object
 4   Job Description    3909 non-null   object
 5   Rating             3909 non-null   float64
 6   Company Name       3909 non-null   object
 7   Location           3909 non-null   object
 8   Headquarters       3909 non-null   object
 9   Size               3909 non-null   object
 10  Founded            3909 non-null   int64
 11  Type of ownership  3909 non-null   object
 12  Industry           3909 non-null   object
 13  Sector             3909 non-null   object
 14  Revenue            3909 non-null   object
 15  Competitors        3909 non-null   object
 16  Easy Apply         3909 non-null   object
dtypes: float64(1), int64(3), object(13)
memory usage: 519.3+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1970 entries, 0 to 1969
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1970 non-null   int64
 1   index                1970 non-null   int64
 2   title                1970 non-null   object
 3   company_name         1970 non-null   object
 4   location             1967 non-null   object
 5   via                  1970 non-null   object
 6   description          1970 non-null   object
 7   extensions           1970 non-null   object
 8   job_id               1970 non-null   object
 9   thumbnail            1126 non-null   object
 10  posted_at            1970 non-null   object
 11  schedule_type        1961 non-null   object
 12  work_from_home       993 non-null    object
 13  salary               382 non-null    object
 14  search_term          1970 non-null   object
 15  date_time            1970 non-null   object
 16  search_location      1970 non-null   object
 17  commute_time         0 non-null      float64
 18  salary_pay           382 non-null    object
 19  salary_rate          382 non-null    object
 20  salary_avg           382 non-null    float64
 21  salary_min           342 non-null    float64
 22  salary_max           342 non-null    float64
 23  salary_hourly        214 non-null    float64
 24  salary_yearly        166 non-null    float64
 25  salary_standardized  382 non-null    float64
 26  description_tokens   1970 non-null   object
dtypes: float64(7), int64(2), object(18)
memory usage: 415.7+ KB

None

In [364]:
#Rename Columns to lower and replace white spaces with Underscore
analyst_df.rename(columns=lambda x : x.lower(), inplace=True)
analyst_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
scientist_df.rename(columns=lambda x : x.lower(), inplace=True)
scientist_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)
jobs_df.rename(columns=lambda x : x.lower(), inplace=True)
jobs_df.rename(columns=lambda x : x.replace(' ', '_'), inplace=True)

jobs_df.rename(columns= {'title':'job_title', 'description':'job_description', 'description':'job_description'}, inplace=True)

In [365]:
data_analyst_df2 = analyst_df[['job_title', 'job_description']].copy()
data_scientist_df2 = scientist_df[['job_title', 'job_description']].copy()
google_job_df2 = jobs_df[['job_title', 'job_description']].copy()

In [366]:
#Join Data Analyst Dataset and Data Scientist Dataset
analyst_scientist_df = pd.concat([data_analyst_df2, data_scientist_df2], ignore_index=True)

In [367]:
#lets rename columns of the google job dataset
# google_job_df2 = google_job_df2.rename(columns={'title': 'job_title', 'description': 'job_description'})

In [368]:
#join google dataset to the data analyst /scientist dataset
master_df = pd.concat([analyst_scientist_df, google_job_df2],ignore_index=True)

In [369]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8132 entries, 0 to 8131
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        8132 non-null   object
 1   job_description  8132 non-null   object
dtypes: object(2)
memory usage: 127.2+ KB

In [370]:
import string
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

In [371]:
analyst_df["job_description"] = analyst_df["job_description"].str.replace("\n", " ")

In [372]:
master_df['job_description'] = master_df['job_description'].replace({'/':' ','-':' '},regex=True)

In [373]:
# Import Libraries
import string # a collection of string constraints: white-space, punctuation, etc.
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
#nltk.download('punkt')   # Required for tokenization
#nltk.download('wordnet') # Required for lemmatization
# nltk.download('popular')
from nltk.corpus import stopwords
# Instantiate
lemmatizer = WordNetLemmatizer()
# Create our own stop words
stop_words = (                                        \
    "\n ’ sleeves company and of for in to a or years l   \
    other were that data to drive policy we at with our   \
    firm follows under consolidated have these over   \
    include billion million december which an le from \
    certain le — million had show apple including     \
    as noncurrent current total three are on not is   \
    involving millions shows centers contains      "  \
             ).split()
# Exclusion list of punctuations and numbers
# exclist = string.punctuation + string.digits # Do we also need digits?
exclude_punctuation = "!$%&'()*,-./:;<=>?@[\]^_`{|}~"
exclist = exclude_punctuation + string.digits # Do we also need digits?
# Print the exclusion list
print(exclist)

!$%&'()*,-./:;<=>?@[\]^_`{|}~0123456789

In [374]:
# Create a Function
def clean_texts(text):
    """ Function to perform preprocessing """
    
    # Convert to lower cases
    text = text.lower()
    
    # Remove punctuations and numbers
    text = text.translate(str.maketrans("", "", exclist))
    
    # White space before and after punctuation?
    # text = text.translate(str.maketrans({key: " {0} ".format(key) for key in string.punctuation}))
    
    
    # Tokenization
    tokens = word_tokenize(text)
        
    # Lemmatization
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Remove stop words
    tokens = [token for token in tokens if token not in stop_words]
    
    # Join tokens
    clean_text = " ".join(tokens)
    
    # Return the output
    return clean_text
# Apply the function to all disclosures
master_df['job_description'] = master_df['job_description'].apply(clean_texts)
# View the first 5 rows
master_df.head()

,job_title,job_description
0,"Data Analyst, Center on Immigration and Justic...",you eager roll up your sleeve harness change d...
1,Quality Data Analyst,overview provides analytical technical support...
2,"Senior Data Analyst, Insights & Analytics Team...",re looking senior analyst who ha love mentorsh...
3,Data Analyst,requisition numberrr remoteyes collaborate cre...
4,Reporting Data Analyst,about fanduel group fanduel group world class ...

In [375]:
# Tried to follow https://realpython.com/nltk-nlp-python/ for using NLTK
nltk.download("stopwords")
from nltk.corpus import stopwords 
from nltk import FreqDist

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/georgeyordel/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [376]:
filtered_list = []

In [377]:
# for word in zero_text:
#     if word.casefold() not in stop_words:
#         filtered_list.append(word)

In [378]:
master_df['description_words'] = master_df["job_description"].apply(word_tokenize)

In [379]:
# master_df['description_words'][0]

In [380]:
# master_df['description_words'] = master_df['description_words'].apply(lambda x: [item for item in x if item not in stop_words])

In [381]:
master_df['description_words'][0]

['you',
 'eager',
 'roll',
 'up',
 'your',
 'sleeve',
 'harness',
 'change',
 'do',
 'you',
 'enjoy',
 'sifting',
 'through',
 'complex',
 'datasets',
 'illuminate',
 'trend',
 'insight',
 'do',
 'you',
 'see',
 'yourself',
 'working',
 'value',
 'driven',
 'organization',
 'vision',
 'tackle',
 'the',
 'most',
 'pressing',
 'injustice',
 'day',
 'looking',
 'hire',
 'bright',
 'hard',
 'working',
 'creative',
 'individual',
 'strong',
 'management',
 'skill',
 'demonstrated',
 'commitment',
 'immigrant',
 'right',
 'the',
 'analyst',
 'will',
 'assist',
 'analysis',
 'reporting',
 'need',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'working',
 'across',
 'it',
 'project',
 'future',
 'vera',
 'initiative',
 'who',
 'founded',
 'the',
 'vera',
 'institute',
 'independent',
 'non',
 'partisan',
 'nonprofit',
 'organization',
 'combine',
 'expertise',
 'research',
 'technical',
 'assistance',
 'demonstration',
 'project',
 'assist',
 'leader',
 'government',
 'civil',
 'society',
 'examine',
 'justice',
 'practice',
 'improve',
 'the',
 'system',
 'people',
 'rely',
 'justice',
 'safety',
 'study',
 'problem',
 'impede',
 'human',
 'dignity',
 'justice',
 'pilot',
 'solution',
 'once',
 'transformative',
 'achievable',
 'engage',
 'diverse',
 'community',
 'informed',
 'debate',
 'harness',
 'the',
 'power',
 'evidence',
 'effective',
 'practice',
 'what',
 'doing',
 'helping',
 'build',
 'movementamong',
 'government',
 'leader',
 'advocate',
 'the',
 'immigration',
 'legal',
 'service',
 'communitytowards',
 'universal',
 'legal',
 'representation',
 'immigrant',
 'facing',
 'deportation',
 'the',
 'face',
 'stepped',
 'up',
 'immigration',
 'enforcement',
 'non',
 'citizen',
 'risk',
 'extended',
 'detention',
 'permanent',
 'separation',
 'their',
 'family',
 'community',
 'veras',
 'center',
 'immigration',
 'justice',
 'cij',
 'partner',
 'government',
 'non',
 'profit',
 'partner',
 'community',
 'improve',
 'government',
 'system',
 'affect',
 'immigrant',
 'their',
 'family',
 'cij',
 'administers',
 'several',
 'nationwide',
 'legal',
 'service',
 'program',
 'immigrant',
 'facing',
 'deportation',
 'develops',
 'implement',
 'pilot',
 'program',
 'provides',
 'technical',
 'assistance',
 'conduct',
 'independent',
 'research',
 'evaluation',
 'thats',
 'where',
 'you',
 'come',
 'the',
 'analyst',
 'will',
 'support',
 'the',
 'center',
 'programmatic',
 'effort',
 'through',
 'regular',
 'monitoring',
 'reporting',
 'federal',
 'government',
 'subcontractor',
 'cij',
 'manages',
 'several',
 'proprietary',
 'database',
 'run',
 'aws',
 'caspio',
 'us',
 'sql',
 'r',
 'python',
 'manage',
 'this',
 'opportunity',
 'help',
 'shape',
 'innovative',
 'national',
 'research',
 'agenda',
 'part',
 'dedicated',
 'team',
 'expert',
 'working',
 'improve',
 'access',
 'justice',
 'non',
 'citizen',
 'vera',
 'seek',
 'hire',
 'analyst',
 'work',
 'various',
 'management',
 'project',
 'it',
 'center',
 'immigration',
 'justice',
 'cij',
 'collaboration',
 'analyst',
 'this',
 'position',
 'will',
 'involve',
 'work',
 'across',
 'several',
 'project',
 'such',
 'the',
 'unaccompanied',
 'childrens',
 'program',
 'ucp',
 'program',
 'increase',
 'legal',
 'representation',
 'immigrant',
 'child',
 'facing',
 'deportation',
 'without',
 'parent',
 'legal',
 'guardian',
 'the',
 'position',
 'may',
 'cover',
 'additional',
 'duty',
 'the',
 'legal',
 'orientation',
 'program',
 'custodian',
 'lopc',
 'educates',
 'the',
 'custodian',
 'unaccompanied',
 'child',
 'about',
 'their',
 'right',
 'the',
 'immigration',
 'court',
 'process',
 'about',
 'the',
 'role',
 'analyst',
 'you',
 'will',
 'report',
 'member',
 'the',
 'research',
 'team',
 'work',
 'close',
 'collaboration',
 'vera',
 'staff',
 'ongoing',
 'database',
 'management',
 'monitoring',
 'reporting',
 'analysis',
 'project',
 'youll',
 'support',
 'the',
 'team',
 'by',
 'taking',
 'ownership',
 'ongoing',
 'monitoring',
 'reporting',
 'task',
 'large',
 'set',
 'principal',
 'responsibility',
 'will',
 'supporting',
 'research',
 'staff',
 'by',
 'preparing',
 'large',
 'datasets',
 'analysis',
 'merging',
 'cleaning',
 'recoding',
 'providing',
 'insight',
 'into',
 'program',
 'performance',
 'through',
 'summary',
 'statistic',
 'performance',
 'indicator',
 'producing',
 'timely',
 'report',
 'vera',
 'project',
 'team',
 'member',
 'stakeholder',
 'improving',
 'recurring',
 'reporting',
 'process',
 'by',
 'optimizing',
 'code',
 'producing',
 'subsequent',
 'documentation',
 'coordinating',
 'database',
 'management',
 'task',
 'such',
 'participating',
 'new',
 'database',
 'design',
 'modifying',
 'existing',
 'database',
 'communicating',
 'outside',
 'engineer',
 'subcontractor',
 'developing',
 'codebooks',
 'delivering',
 'user',
 'training',
 'through',
 'webinars',
 'database',
 'guide',
 'building',
 'maintaining',
 'interactive',
 'dashboard',
 'documenting',
 'correcting',
 'quality',
 'issue',
 'working',
 'supervisor',
 'prioritize',
 'program',
 'need',
 'assisting',
 'project',
 'task',
 'assigned',
 'about',
 'you',
 'youre',
 'committed',
 'improving',
 'issue',
 'affecting',
 'immigrant',
 'the',
 'united',
 'state',
 'applicant',
 'personal',
 'experience',
 'the',
 'immigration',
 'system',
 'especially',
 'encouraged',
 'apply',
 'youre',
 'just',
 'getting',
 'started',
 'your',
 'career',
 'year',
 'professional',
 'internship',
 'experience',
 'working',
 'large',
 'datasets',
 'preparing',
 'analysis',
 'you',
 'real',
 'enthusiasm',
 'working',
 'you',
 'comfortable',
 'writing',
 'query',
 'sql',
 'r',
 'python',
 'solid',
 'foundation',
 'coding',
 'programming',
 'language',
 'used',
 'manipulate',
 'experience',
 'working',
 'collaboratively',
 'using',
 'tool',
 'like',
 'git',
 'github',
 'plus',
 'you',
 'exceptional',
 'attention',
 'detail',
 'strong',
 'problem',
 'solving',
 'ability',
 'logical',
 'reasoning',
 'skill',
 'the',
 'ability',
 'detect',
 'anomaly',
 'youre',
 'able',
 'work',
 'multiple',
 'project',
 'effectively',
 'efficiently',
 'both',
 'independently',
 'collaboratively',
 'team',
 'this',
 'position',
 'involves',
 'working',
 'secure',
 'may',
 'require',
 'government',
 'security',
 'clearance',
 'clearance',
 'restricted',
 'u',
 'citizen',
 'citizen',
 'country',
 'party',
 'collective',
 'defense',
 'agreement',
 'the',
 'u',
 'the',
 'list',
 'those',
 'country',
 'detailed',
 'this',
 'webpage',
 'additional',
 'requirement',
 'clearance',
 'residence',
 'the',
 'united',
 'state',
 'least',
 'the',
 'last',
 'five',
 'year',
 'how',
 'apply',
 'please',
 'submit',
 'cover',
 'letter',
 'resume',
 'application',
 'will',
 'be',
 'considered',
 'rolling',
 'basis',
 'until',
 'position',
 'filled',
 'online',
 'submission',
 'pdf',
 'format',
 'preferred',
 'application',
 'no',
 'cover',
 'letter',
 'attached',
 'will',
 'be',
 'considered',
 'the',
 'cover',
 'letter',
 'should',
 'address',
 'your',
 'interest',
 'cij',
 'this',
 'position',
 'however',
 'if',
 'necessary',
 'material',
 'may',
 'be',
 'mailed',
 'faxed',
 'attn',
 'human',
 'resource',
 'cij',
 'analyst',
 'recruitment',
 'vera',
 'institute',
 'justice',
 'th',
 'st',
 'suite',
 'brooklyn',
 'ny',
 'fax',
 'please',
 'use',
 'only',
 'one',
 'method',
 'online',
 'mail',
 'fax',
 'submission',
 'no',
 'phone',
 'call',
 'please',
 'only',
 'applicant',
 'selected',
 'interview',
 'will',
 'be',
 'contacted',
 'vera',
 'equal',
 'opportunity',
 'affirmative',
 'action',
 'employer',
 'all',
 'qualified',
 'applicant',
 'will',
 'be',
 'considered',
 'employment',
 'without',
 'unlawful',
 'discrimination',
 'based',
 'race',
 'color',
 'creed',
 'national',
 'origin',
 'sex',
 'age',
 'disability',
 'marital',
 'status',
 'sexual',
 'orientation',
 'military',
 'status',
 'prior',
 'record',
 'arrest',
 'conviction',
 'citizenship',
 'status',
 'employment',
 'status',
 'caregiver',
 'status',
 'vera',
 'work',
 'advance',
 'justice',
 'particularly',
 'racial',
 'justice',
 'increasingly',
 'multicultural',
 'country',
 'globally',
 'connected',
 'world',
 'value',
 'diverse',
 'experience',
 'regard',
 'educational',
 'background',
 'justice',
 'system',
 'contact',
 'depend',
 'diverse',
 'staff',
 'carry',
 'out',
 'mission',
 'more',
 'information',
 'about',
 'vera',
 'cijs',
 'work',
 'please',
 'visit',
 'wwwveraorg',
 'powered',
 'by',
 'jazzhr']

In [382]:
nltk.FreqDist(master_df['description_words'][0])

FreqDist({'the': 25, 'justice': 11, 'you': 9, 'working': 9, 'will': 9, 'vera': 9, 'project': 8, 'immigration': 7, 'cij': 7, 'program': 7, ...})

In [383]:
my_languages = ["abap", "actionscript", "ada", "algol", "alice", "apl", "asp", "aspnet", "assembly" "language",
                "assembly language", "awk", "bbc", "bbcbasic", "bbc basic", "c", "c++", "c#", "cobol", "delphi", # "d"
                "dreamweaver", "erlang", "elixir", "erlang and elixir", "f#", "forth", "fortran", # "functional", "programming"
                "functional programming", "haskell", "html", "idl", "idl", "intercal", "java", "javascript", "node", "js", # "go"
                "node.js", "jquery", "bootstrap" "labview","lisp","metaquotes language","metaquoteslanguage","ml","modula-3",
                "msaccess","ms access","mysql","nxt-g","object-oriented programming","objective-c","ocaml","pascal","perl",
                "php","pl/sql","postgresql","postscript","prolog","puredata","python","r","rapidweaver","ravendb","rexx",
                "ruby on rails","Rubyonrails","s-plus","sas","scala","sed","sgml","simula","smalltalk","smil","snobol",
                "sql","sqlite","ssi","stata","swift","tcl/tk","tex and latex","texandlatex","unified modeling language",
                "unix shells","unixshells","verilog","vhdl","visualbasi","visual basis","vrml","wap/wml","xml","xsl",
                "julia"]

In [384]:
my_tools = ["microsoft excel", "excel", "tableau", # "microsoft"
            "rapidminer", "knime", "power bi", "bi", "apache spark",
            "apache", "spark", "qlikview", "qlik", "talend", "splunk", "businessobjects",
            "sap", "sap businessobjects", "sisense", "tibco spotfire", "tibco",
            "spotfire", "thoughtspot", "sas business intelligence", "sas", "business intelligence",
            "google data studio", "data studio", "google analytics", "redash", "periscope data",
            "periscope", "metabase", "jupyter notebook", "jupyter", "notebook", "ibm cognos", "ibm",
            "cognos", "chartio", "mode", "looker", "domo", "oracle analytics cloud", "oracle",
            "oracle analytics", "analytics cloud", "oracle cloud", "github" # "git"]

In [385]:
my_databases = ["mysql", "postgresql", "microsoft sql server", "sql server", "mongodb", "mongo",
                "oracle", "remote dictionary server", "redis", "elasticsearch", "mariadb",
                "ibm db2", "sqlite", "amazon dynamodb", "dynamodb", "aws", "azure cosmos db",
                "azure", "cosmos", "cosmos db", "azure cosmos", "azure db", "azuredb",
                "amazon keyspaces", "keyspaces", "amazon documentdb", "documentdb", "amazon redshift",
                "redshift", "cassandra", "hbase", "neo4j", "couchdb", "orientdb", "terrstore",
                "flockdb", "hibari", "riak"]

In [386]:
my_softskills = ["communication", "curiosity", "business acumen", "storytelling",
                "adaptability", "critical thinking", "product understanding", "team plater",
                "problem solving", "problem-solving", "research oriented", "attention to detail", # "research"
                "teamwork", "critical-thinking", "data visualizations", "data visualisations", ]

In [387]:
master_df['description_languages'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_languages])
master_df['description_tools'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_tools])
master_df['description_databases'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_databases])
master_df['description_softskills'] = master_df['description_words'].apply(lambda x: [item for item in x if item in my_softskills])

In [388]:
master_df['description_languages'][0]

['sql', 'r', 'python', 'sql', 'r', 'python']

In [389]:
master_df

,job_title,job_description,description_words,description_languages,description_tools,description_databases,description_softskills
0,"Data Analyst, Center on Immigration and Justic...",you eager roll up your sleeve harness change d...,"[you, eager, roll, up, your, sleeve, harness, ...","[sql, r, python, sql, r, python]","[git, github]",[aws],[]
1,Quality Data Analyst,overview provides analytical technical support...,"[overview, provides, analytical, technical, su...","[sql, sql, r, stata]","[excel, excel, excel, excel]",[],[communication]
2,"Senior Data Analyst, Insights & Analytics Team...",re looking senior analyst who ha love mentorsh...,"[re, looking, senior, analyst, who, ha, love, ...","[sql, r, python, sql, r, python]","[excel, bi, bi, chartio, looker, tableau]",[],[curiosity]
3,Data Analyst,requisition numberrr remoteyes collaborate cre...,"[requisition, numberrr, remoteyes, collaborate...","[sql, sql, sql]",[tableau],[],"[curiosity, teamwork, communication]"
4,Reporting Data Analyst,about fanduel group fanduel group world class ...,"[about, fanduel, group, fanduel, group, world,...","[sql, sql, python]",[excel],[],[]
...,...,...,...,...,...,...,...
8127,Senior Performance Marketing (Data Analyst),edward jones help client achieve their serious...,"[edward, jones, help, client, achieve, their, ...","[sql, sql, xml, r, python]","[oracle, excel, tableau]",[oracle],[communication]
8128,"Data Analyst, Developer Operations",summary meta platform inc meta formerly known ...,"[summary, meta, platform, inc, meta, formerly,...","[sql, python]","[tableau, qlikview]",[],[]
8129,Data Science/Data Analyst Internship - Summer ...,description who koch industry mission help peo...,"[description, who, koch, industry, mission, he...",[],[],[],"[curiosity, communication]"
8130,2023 Internship- Associate Data Analyst,internship associate analyst description job s...,"[internship, associate, analyst, description, ...","[sql, r, python, sql, c]","[bi, bi, bi, tableau]",[],[communication]
8131,Jr. Data Analyst,staffigo the business providing it consulting ...,"[staffigo, the, business, providing, it, consu...",[],"[excel, oracle, bi, tableau]",[oracle],"[teamwork, communication]"

In [390]:
master_df.head(20)

,job_title,job_description,description_words,description_languages,description_tools,description_databases,description_softskills
0,"Data Analyst, Center on Immigration and Justic...",you eager roll up your sleeve harness change d...,"[you, eager, roll, up, your, sleeve, harness, ...","[sql, r, python, sql, r, python]","[git, github]",[aws],[]
1,Quality Data Analyst,overview provides analytical technical support...,"[overview, provides, analytical, technical, su...","[sql, sql, r, stata]","[excel, excel, excel, excel]",[],[communication]
2,"Senior Data Analyst, Insights & Analytics Team...",re looking senior analyst who ha love mentorsh...,"[re, looking, senior, analyst, who, ha, love, ...","[sql, r, python, sql, r, python]","[excel, bi, bi, chartio, looker, tableau]",[],[curiosity]
3,Data Analyst,requisition numberrr remoteyes collaborate cre...,"[requisition, numberrr, remoteyes, collaborate...","[sql, sql, sql]",[tableau],[],"[curiosity, teamwork, communication]"
4,Reporting Data Analyst,about fanduel group fanduel group world class ...,"[about, fanduel, group, fanduel, group, world,...","[sql, sql, python]",[excel],[],[]
5,Data Analyst,about cubist cubist systematic strategy one th...,"[about, cubist, cubist, systematic, strategy, ...","[sql, python, c, c++, java]",[excel],[],"[communication, communication]"
6,Business/Data Analyst (FP&A),two sigma different kind investment manager si...,"[two, sigma, different, kind, investment, mana...","[python, sql]",[excel],[],[communication]
7,Data Science Analyst,science analyst job detail level experienced j...,"[science, analyst, job, detail, level, experie...","[r, python, sql]",[],[],[]
8,Data Analyst,the analyst integral member the global commerc...,"[the, analyst, integral, member, the, global, ...","[sql, python, r, scala]","[excel, spark]",[],[]
9,"Data Analyst, Merchant Health",about u riskified the ai platform powering the...,"[about, u, riskified, the, ai, platform, power...","[r, sql, sql, r, python]",[],[],[communication]
10,Data Analyst,nyu grossman school medicine one the nation s ...,"[nyu, grossman, school, medicine, one, the, na...","[stata, r]",[],[],[communication]
11,Data Analyst,bulbhead currently seeking analyst join team a...,"[bulbhead, currently, seeking, analyst, join, ...","[sql, python, sql, python, r, sql, python]","[excel, tableau, chartio, looker]",[],"[curiosity, communication, storytelling]"
12,DATA ANALYST,job summary the clinical research analyst the ...,"[job, summary, the, clinical, research, analys...",[],[],[],[]
13,Senior Data Analyst,about known known modern marketing engineered ...,"[about, known, known, modern, marketing, engin...","[python, sql]",[excel],[],[communication]
14,Investment Advisory Data Analyst,investment advisory compliance opportunity fin...,"[investment, advisory, compliance, opportunity...",[sql],[excel],[],[communication]
15,Sustainability Data Analyst,job description role description sustainabilit...,"[job, description, role, description, sustaina...","[sql, r, python]",[excel],[],[communication]
16,Data Analyst,undertone stand alone among adtech ad network ...,"[undertone, stand, alone, among, adtech, ad, n...","[sql, sql]","[tableau, tableau]",[],[communication]
17,Clinical Data Analyst,about u nystec non profit technology consultin...,"[about, u, nystec, non, profit, technology, co...","[sql, python]",[],[],[communication]
18,DATA PROGRAMMER/ANALYST,description education development center edc e...,"[description, education, development, center, ...","[python, java]",[],[],[communication]
19,Data Analyst,about u teacher pay teacher tpt unlocking the ...,"[about, u, teacher, pay, teacher, tpt, unlocki...","[sql, python, r, ml]","[bi, looker]",[],"[teamwork, communication]"

In [391]:
master_df["job_description"][0]

'you eager roll up your sleeve harness change do you enjoy sifting through complex datasets illuminate trend insight do you see yourself working value driven organization vision tackle the most pressing injustice day looking hire bright hard working creative individual strong management skill demonstrated commitment immigrant right the analyst will assist analysis reporting need veras center immigration justice cij working across it project future vera initiative who founded the vera institute independent non partisan nonprofit organization combine expertise research technical assistance demonstration project assist leader government civil society examine justice practice improve the system people rely justice safety study problem impede human dignity justice pilot solution once transformative achievable engage diverse community informed debate harness the power evidence effective practice what doing helping build movementamong government leader advocate the immigration legal service communitytowards universal legal representation immigrant facing deportation the face stepped up immigration enforcement non citizen risk extended detention permanent separation their family community veras center immigration justice cij partner government non profit partner community improve government system affect immigrant their family cij administers several nationwide legal service program immigrant facing deportation develops implement pilot program provides technical assistance conduct independent research evaluation thats where you come the analyst will support the center programmatic effort through regular monitoring reporting federal government subcontractor cij manages several proprietary database run aws caspio us sql r python manage this opportunity help shape innovative national research agenda part dedicated team expert working improve access justice non citizen vera seek hire analyst work various management project it center immigration justice cij collaboration analyst this position will involve work across several project such the unaccompanied childrens program ucp program increase legal representation immigrant child facing deportation without parent legal guardian the position may cover additional duty the legal orientation program custodian lopc educates the custodian unaccompanied child about their right the immigration court process about the role analyst you will report member the research team work close collaboration vera staff ongoing database management monitoring reporting analysis project youll support the team by taking ownership ongoing monitoring reporting task large set principal responsibility will supporting research staff by preparing large datasets analysis merging cleaning recoding providing insight into program performance through summary statistic performance indicator producing timely report vera project team member stakeholder improving recurring reporting process by optimizing code producing subsequent documentation coordinating database management task such participating new database design modifying existing database communicating outside engineer subcontractor developing codebooks delivering user training through webinars database guide building maintaining interactive dashboard documenting correcting quality issue working supervisor prioritize program need assisting project task assigned about you youre committed improving issue affecting immigrant the united state applicant personal experience the immigration system especially encouraged apply youre just getting started your career year professional internship experience working large datasets preparing analysis you real enthusiasm working you comfortable writing query sql r python solid foundation coding programming language used manipulate experience working collaboratively using tool like git github plus you exceptional attention detail strong problem solving ability logical reasoning skill the ability detect anomaly youre able work multiple project effectively efficiently both independently collaboratively team this position involves working secure may require government security clearance clearance restricted u citizen citizen country party collective defense agreement the u the list those country detailed this webpage additional requirement clearance residence the united state least the last five year how apply please submit cover letter resume application will be considered rolling basis until position filled online submission pdf format preferred application no cover letter attached will be considered the cover letter should address your interest cij this position however if necessary material may be mailed faxed attn human resource cij analyst recruitment vera institute justice th st suite brooklyn ny fax please use only one method online mail fax submission no phone call please only applicant selected interview will be contacted vera equal opportunity affirmative action employer all qualified applicant will be considered employment without unlawful discrimination based race color creed national origin sex age disability marital status sexual orientation military status prior record arrest conviction citizenship status employment status caregiver status vera work advance justice particularly racial justice increasingly multicultural country globally connected world value diverse experience regard educational background justice system contact depend diverse staff carry out mission more information about vera cijs work please visit wwwveraorg powered by jazzhr'

In [392]:
google_job_df2

,job_title,job_description
0,Data Analyst,Job Posting Title\nData Analyst\n...\nAgency\n...
1,Data Analyst (Marketing),About The Role\n\nAbout Us...\n\nWe’re Entain....
2,People Analytics Data Analyst (Talent Acquisit...,Job Description\nPeople Analytics CoE (Communi...
3,Data Analyst,Pernod Ricard is now hiring Data Analyst in Un...
4,Sr Systems Data Analyst,Type of Requisition: Regular\n\nClearance Leve...
...,...,...
1965,Senior Performance Marketing (Data Analyst),"At Edward Jones, we help clients achieve their..."
1966,"Data Analyst, Developer Operations","Summary:\n\nMeta Platforms, Inc. (Meta), forme..."
1967,Data Science/Data Analyst Internship - Summer ...,Description\n\nWho are we...\n\nAt Koch Indust...
1968,2023 Internship- Associate Data Analyst,2023 Internship- Associate Data Analyst\n\nDes...
1969,Jr. Data Analyst,Staffigo is in the business of providing IT Co...

In [393]:
master_df['job_description'][18]

'description education development center edc edc one the world s leading nonprofit research development edc design implement evaluates program improve education health economic opportunity worldwide collaborating both public private partner strive world where all people empowered live healthy productive life the center child technology cct research development center within edc based new york city conduct basic applied casual formative research working collaboration educational corporate government research institution also design develop prototype software instructional resource support engaged active learning edc committed diversity the workplace job description the center child technology edc s u division ha opening part time temporary analyst reporting the lead researcher the new york office edccct seeking part time temporary analyst support analysis study using large scale the study s focus explore middle school mathematics learning order identify way meet the need struggling mathematics student this opening ideal graduate student individual interested gaining research experience leverage large scale this position based new york city requires the analysis be conducted site edc casual employee generally work needed this position will offer average hour week approximately january may possibility extension the actual hour per week duration will vary depending phase need the project will likely be more the first month the project later month casual position receives statutory benefit social security contribution medicare contribution unemployment insurance worker s compensation insurance sick leave casual position end when work complete essential function the person this position expected communicate clearly courteously develop maintain positive relationship client consultant collaborator co worker field site funders work respectfully edc colleague the job requires adherence edc procedure management guidance the analyst provides support extracting cleaning analyzing large datasets gb+ specific responsibility • assist lead research associate extraction large set • develop script clean manipulate large set merging aggregating splitting large file into chunk analysis • develop script conduct basic descriptive analysis possibly aggregating analysis across chunked file • document share analytic approach colleague so they can replicate the process • provide solution reducing memory use analyzing large datasets qualification this position requires educational achievement excellent writing skill demonstrable initiative creativity flexibility ability work independently effectively group strong interpersonal organizational skill specific requirement • degree required bachelor computer science statistic related field • degree preferred master computer science statistic related field • year experience programming analyzing research industry • thorough understanding cleaning analyzing large scale • experience least one programming language used very large datasets python java etc • experience mining large set team setting • strong organizational skill problem solving skill • excellent oral written communication skill • conduct analysis meet colleague site the new york office additional information all your information will be kept confidential according eeo guideline'

In [ ]:
master_df.query('')